### ISSUE TITLE
python cli_demo.py报jittor 编译错误

### ISSUE THREAD

**Issue by IUgly** [Jittor/JittorLLMs#108]
`JittorLLMs]# python cli_demo.py chatglm
[i 0513 13:38:43.964825 64 compiler.py:955] Jittor(1.3.7.16) src: /root/JittorLLMs/myenv/lib/python3.10/site-packages/jittor
[i 0513 13:38:43.968178 64 compiler.py:956] g++ at /usr/bin/g++(8.5.0)
[i 0513 13:38:43.968239 64 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++8.5.0/py3.10.9/Linux-5.4.203-xa2/IntelRXeonRPlax40/main
[i 0513 13:38:43.971742 64 __init__.py:411] Found nvcc(11.0.221) at /usr/local/cuda/bin/nvcc.
[i 0513 13:38:44.052111 64 __init__.py:411] Found gdb(9.2) at /usr/bin/gdb.
[i 0513 13:38:44.055567 64 __init__.py:411] Found addr2line(2.35) at /usr/bin/addr2line.
[i 0513 13:38:44.176889 64 compiler.py:1010] cuda key:cu11.0.221_sm_
Traceback (most recent call last):
  File "/root/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/root/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/root/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/root/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/root/JittorLLMs/myenv/lib/python3.10/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/root/JittorLLMs/myenv/lib/python3.10/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/root/JittorLLMs/myenv/lib/python3.10/site-packages/jittor/compiler.py", line 891, in check_cache_compile
    assert jit_utils.cc
AssertionError`

**Comment by luckytalk** [comment]
我也遇到同样问题？
