### ISSUE TITLE
cli_demo.py chatglm 升级到1.3.7.4后仍然报错

### ISSUE THREAD

**Issue by JulyFinal** [Jittor/JittorLLMs#11]
```
❯ python cli_demo.py chatglm
[i 0404 17:43:26.955718 72 compiler.py:955] Jittor(1.3.7.4) src: /home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor
[i 0404 17:43:26.957501 72 compiler.py:956] g++ at /usr/bin/g++(7.5.0)
[i 0404 17:43:26.957551 72 compiler.py:957] cache_path: /home/final/.cache/jittor/jt1.3.7/g++7.5.0/py3.10.10/Linux-5.14.21-x35/IntelRCoreTMi7x56/default
[i 0404 17:43:26.959628 72 __init__.py:411] Found /usr/local/cuda/bin/nvcc(11.8.89) at /usr/local/cuda/bin/nvcc.
[i 0404 17:43:27.012448 72 __init__.py:411] Found gdb(12.1) at /usr/bin/gdb.
[i 0404 17:43:27.014705 72 __init__.py:411] Found addr2line(150100.7.40) at /usr/bin/addr2line.
[i 0404 17:43:27.150051 72 compiler.py:1010] cuda key:cu11.8.89_sm_
[i 0404 17:43:27.322970 72 __init__.py:227] Total mem: 15.33GB, using 5 procs for compiling.
[i 0404 17:43:27.393922 72 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0404 17:43:27.471475 72 init.cc:62] Found cuda archs: []
[i 0404 17:43:27.569246 72 compile_extern.py:522] mpicc not found, distribution disabled.
Traceback (most recent call last):
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/compile_extern.py", line 235, in setup_cuda_extern
    setup_cuda_lib(lib_name, extra_flags=link_cuda_extern)
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/compile_extern.py", line 266, in setup_cuda_lib
    cuda_include_name = search_file([cuda_include, extra_include_path, "/usr/include"], lib_name+".h")
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/compile_extern.py", line 32, in search_file
    LOG.f(f"file {name} not found in {dirs}")
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor_utils/__init__.py", line 104, in f
    def f(self, *msg): self._log('f', 0, *msg)
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor_utils/__init__.py", line 89, in _log
    cc.log(fileline, level, verbose, msg)
RuntimeError: [f 0404 17:43:27.615175 72 compile_extern.py:32] file cudnn.h not found in ['/usr/local/cuda/include', '/usr/local/cuda/targets/x86_64-linux/include', '/usr/include']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/final/workspace/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/final/workspace/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/home/final/workspace/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/home/final/workspace/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/__init__.py", line 25, in <module>
    from . import compile_extern
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/compile_extern.py", line 596, in <module>
    setup_cuda_extern()
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor/compile_extern.py", line 247, in setup_cuda_extern
    LOG.f(msg)
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor_utils/__init__.py", line 104, in f
    def f(self, *msg): self._log('f', 0, *msg)
  File "/home/final/miniforge3/envs/py310/lib/python3.10/site-packages/jittor_utils/__init__.py", line 89, in _log
    cc.log(fileline, level, verbose, msg)
RuntimeError: [f 0404 17:43:27.615244 72 compile_extern.py:247] CUDA found but cudnn is not loaded:
Develop version of CUDNN not found,
please refer to CUDA offical tar file installation:
https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux-tar
or you can let jittor install cuda and cudnn for you:
>>> python3.10 -m jittor_utils.install_cuda
```

当前版本：
```
Python3.10
jittor == 1.3.7.4
jtorch == 0.1.3
```

**Comment by Exusial** [comment]
您好，您好像没有安装cudnn，可以用python3.10 -m jittor_utils.install_cuda让jittor帮忙安装

**Comment by JulyFinal** [comment]
> 您好，您好像没有安装cudnn，可以用python3.10 -m jittor_utils.install_cuda让jittor帮忙安装
您好，
结果是这样的
```
> python3.10 -m jittor_utils.install_cuda
[i 0404 19:08:33.135518 44 install_cuda.py:162] nvcc is installed at None
```

不好意思，我不太懂这种不需要显卡的程序是否需要我安装cudnn。

**Comment by cjld** [comment]
您环境里面安装了cuda，但是jittor没有找到显卡，您可以试试`export nvcc_path=`，完全关闭显卡检测试试？

**Comment by JulyFinal** [comment]
> 您环境里面安装了cuda，但是jittor没有找到显卡，您可以试试`export nvcc_path=`，完全关闭显卡检测试试？

我应该没有装过，因为我这个电脑只有核显。 
这个是需要我装一个cuda 然后指定一个目录给他是吗，我先这样试试。

**Comment by JulyFinal** [comment]
> > 您环境里面安装了cuda，但是jittor没有找到显卡，您可以试试`export nvcc_path=`，完全关闭显卡检测试试？
> 
> 我应该没有装过，因为我这个电脑只有核显。 这个是需要我装一个cuda 然后指定一个目录给他是吗，我先这样试试。

解决了 suse不知道为啥自己有一个nvcc 卸载就好了
