### ISSUE TITLE
问问题后报错

### ISSUE THREAD

**Issue by duxiaowu** [Jittor/JittorLLMs#113]
[e 0516 13:46:47.609943 16 mem_info.cc:101] appear time -> node cnt: {1:710, }
Traceback (most recent call last):
  File "/home/duweibin/JittorLLMs/cli_demo.py", line 9, in <module>
    model.chat()
  File "/home/duweibin/JittorLLMs/models/chatglm/__init__.py", line 36, in chat
    for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
  File "/home/duweibin/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1259, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "/home/duweibin/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1334, in stream_generate
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
  File "/home/duweibin/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1083, in prepare_inputs_for_generation
    mask_token = MASK if MASK in input_ids else gMASK
  File "/home/duweibin/.local/lib/python3.9/site-packages/jittor/misc.py", line 132, in __contains__
    return bool((x == key).any())
  File "/home/duweibin/.local/lib/python3.9/site-packages/jittor/__init__.py", line 2013, in to_bool
    return ori_bool(v.item())
RuntimeError: [f 0516 13:46:47.610098 16 executor.cc:682]
Execute fused operator(89/257) failed.
[JIT Source]: /home/duweibin/.cache/jittor/jt1.3.7/g++7.5.0/py3.9.16/Linux-5.4.0-13xf6/IntelRCoreTMi5x26/default/jit/__opkey0_unary__Tx_float16__Ty_float32__OP_cast__JIT_1__JIT_cpu_1__graph_010000___var_info___hash_bc5c187fee6b4175_op.cc
[OP TYPE]: fused_op:( unary.cast,)
[Input]: float16[4096,16384,],
[Output]: float32[4096,16384,]transformer.layers.9.mlp.dense_4h_to_h.weight,
[Async Backtrace]: ---
     /home/duweibin/JittorLLMs/cli_demo.py:8 <<module>>
     /home/duweibin/JittorLLMs/models/__init__.py:46 <get_model>
     /home/duweibin/JittorLLMs/models/chatglm/__init__.py:48 <get_model>
     /home/duweibin/JittorLLMs/models/chatglm/__init__.py:26 <__init__>
     /home/duweibin/.local/lib/python3.9/site-packages/jittor/__init__.py:1730 <float32>
[Reason]: [f 0516 13:46:47.012486 16 swap.cc:63] Check failed: res==1  failed to write swap file /home/duweibin/.cache/jittor/jt1.3.7/g++7.5.0/py3.9.16/Linux-5.4.0-13xf6/IntelRCoreTMi5x26/default/tmp/29197-11719.bin 0 268435456 Var(11719:1:1:1:i0:o0:s1:n0,float32,transformer.layers.9.mlp.dense_h_to_4h.weight,7f3fb1ffb040)[16384,4096,]{/home/duweibin/JittorLLMs/cli_demo.py:8(<module>) -> /home/duweibin/JittorLLMs/models/__init__.py:46(get_model) -> /home/duweibin/JittorLLMs/models/chatglm/__init__.py:48(get_model) -> /home/duweibin/JittorLLMs/models/chatglm/__init__.py:26(__init__) -> /home/duweibin/.local/lib/python3.9/site-packages/jittor/__init__.py:1730(float32) -> }

**Comment by running-frog** [comment]
我也是同样问题，难道没有人解决吗？

**Comment by haiwen-yang** [comment]
加1

**Comment by GreatAsia** [comment]
[e 0702 10:05:07.247670 00 mem_info.cc:101] appear time → node cnt: {2:494, }
Traceback (most recent call last):
File “/Users/zhou/Documents/JittorLLMs/JittorLLMs/cli_demo.py”, line 9, in
model.chat()
File “/Users/zhou/Documents/JittorLLMs/JittorLLMs/models/chatglm/init.py”, line 36, in chat
for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
File “/Users/zhou/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py”, line 1259, in stream_chat
for outputs in self.stream_generate(**input_ids, **gen_kwargs):
File “/Users/zhou/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py”, line 1334, in stream_generate
model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
File “/Users/zhou/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py”, line 1083, in prepare_inputs_for_generation
mask_token = MASK if MASK in input_ids else gMASK
File “/usr/local/lib/python3.9/site-packages/jittor/misc.py”, line 132, in contains
return bool((x == key).any())
File “/usr/local/lib/python3.9/site-packages/jittor/init.py”, line 2013, in to_bool
return ori_bool(v.item())
RuntimeError: [f 0702 10:05:07.247871 00 executor.cc:682]
Execute fused operator(197/257) failed.
[JIT Source]: /Users/zhou/.cache/jittor/jt1.3.7/clang14.0.3/py3.9.14/macOS-13.4.1-xx8e/IntelRCoreTMi5x81/default/jit/__opkey0_unary__Tx_float16__Ty_float32__OP_cast__JIT_1__JIT_cpu_1__graph_010000___var_info___hash_fb103b06255339ba_op.cc
[OP TYPE]: fused_op:( unary.cast,)
[Input]: float16[4096,16384,],
[Output]: float32[4096,16384,]transformer.layers.21.mlp.dense_4h_to_h.weight,
[Async Backtrace]: —
/Users/zhou/Documents/JittorLLMs/JittorLLMs/cli_demo.py:8 <>
/Users/zhou/Documents/JittorLLMs/JittorLLMs/models/init.py:46 <get_model>
/Users/zhou/Documents/JittorLLMs/JittorLLMs/models/chatglm/init.py:48 <get_model>
/Users/zhou/Documents/JittorLLMs/JittorLLMs/models/chatglm/init.py:26 <init>
/usr/local/lib/python3.9/site-packages/jittor/init.py:1730
[Reason]: [f 0702 10:05:07.243268 00 swap.cc:63] Check failed: res==1 failed to write swap file /Users/zhou/.cache/jittor/jt1.3.7/clang14.0.3/py3.9.14/macOS-13.4.1-xx8e/IntelRCoreTMi5x81/default/tmp/32714-11943.bin 0 268435456 Var(11943:1:1:1:i0:o0:s1:n0,float32,transformer.layers.19.mlp.dense_4h_to_h.weight,7f7dedf00000)[4096,16384,]{/Users/zhou/Documents/JittorLLMs/JittorLLMs/cli_demo.py:8() → /Users/zhou/Documents/JittorLLMs/JittorLLMs/models/init.py:46(get_model) → /Users/zhou/Documents/JittorLLMs/JittorLLMs/models/chatglm/init.py:48(get_model) → /Users/zhou/Documents/JittorLLMs/JittorLLMs/models/chatglm/init.py:26(init) → /usr/local/lib/python3.9/site-packages/jittor/init.py:1730(float32) → }

**Comment by nashsophie** [comment]
遇到同样的问题，内存64G，显卡2060，6g显存
