### ISSUE TITLE
centos7 启动用户输入一句直接报错

### ISSUE THREAD

**Issue by cmmsky** [Jittor/JittorLLMs#114]
[i 0518 10:10:26.348652 20 cuda_flags.cc:39] CUDA enabled.
用户输入:1+1
Traceback (most recent call last):
  File "cli_demo.py", line 9, in <module>
    model.chat()
  File "/root/chatglm/JittorLLMs/models/chatglm/__init__.py", line 36, in chat
    for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1259, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1336, in stream_generate
    outputs = self(
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/nn/__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1138, in forward
    transformer_outputs = self.transformer(
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/nn/__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 973, in forward
    layer_ret = layer(
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/nn/__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 614, in forward
    attention_outputs = self.attention(
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/nn/__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 454, in forward
    cos, sin = self.rotary_emb(q1, seq_len=position_ids.max() + 1)
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/nn/__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "/root/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 202, in forward
    t = torch.arange(seq_len, device=x.device, dtype=self.inv_freq.dtype)
  File "/root/anaconda3/lib/python3.8/site-packages/jtorch/__init__.py", line 31, in inner
    ret = func(*args, **kw)
  File "/root/anaconda3/lib/python3.8/site-packages/jittor/misc.py", line 809, in arange
    if isinstance(start, jt.Var): start = start.item()
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.item)).

Types of your inputs are:
 self	= Var,
 args	= (),

The function declarations are:
 ItemData item()

Failed reason:[f 0518 10:10:39.778892 20 parallel_compiler.cc:330] Error happend during compilation:
 [Error] source file location:/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35/jit/__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_3__opkey1_binary__Tx_float16__Ty_float16_____hash_f3d27a3882838ef3_op.cc
Compile fused operator(16/19)failed:[Op(12216:0:1:1:i1:o1:s0,broadcast_to->12217),Op(12218:0:1:1:i2:o1:s0,binary.add->12219),]

Reason: [f 0518 10:10:39.764974 00:C3 log.cc:605] Check failed: ret>=0 && ret<=256  Run cmd failed: "/root/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc" "/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35/jit/__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_3__opkey1_binary__Tx_float16__Ty_float16_____hash_f3d27a3882838ef3_op.cc"      -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/root/anaconda3/lib/python3.8/site-packages/jittor/src" -I/root/anaconda3/include/python3.8 -I/root/anaconda3/include/python3.8 -DHAS_CUDA -DIS_CUDA -I"/root/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/root/anaconda3/lib/python3.8/site-packages/jittor/extern/cuda/inc"  -lcudart -L"/root/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64" -Xlinker -rpath="/root/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/lib64"  -I"/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35" -L"/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35" -Xlinker -rpath="/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35" -L"/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default" -Xlinker -rpath="/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default"  -l:"jit_utils_core.cpython-38-x86_64-linux-gnu".so  -l:"jittor_core.cpython-38-x86_64-linux-gnu".so  -x cu --cudart=shared -ccbin="/usr/bin/g++" --use_fast_math  -w  -I"/root/anaconda3/lib/python3.8/site-packages/jittor/extern/cuda/inc"  -arch=compute_35  -code=sm_35   -o "/root/.cache/jittor/jt1.3.7/g++5.2.0/py3.8.3/Linux-3.10.0-1x21/IntelRCoreTMi7x4b/default/cu11.2.152_sm_35/jit/__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_3__opkey1_binary__Tx_float16__Ty_float16_____hash_f3d27a3882838ef3_op.so"
return -1. This might be an overcommit issue or out of memory. Try : sudo sysctl vm.overcommit_memory=1, or set enviroment variable `export DISABLE_MULTIPROCESSING=1`

**Comment by zrr1999** [comment]
我也遇到了同样的问题，发现是gcc13和cuda12冲突导致的。
我的解决方法是，删除文件夹 /root/.cache/jittor/jt1.3.7/，安装gcc12，设置环境变量 export cc_path="$(which g++-12)"，你可以试试，不过你的cuda11.2不知道是否支持gcc12
