### ISSUE TITLE
按照readme跑 cli_demo直接报错

### ISSUE THREAD

**Issue by tonylin52** [Jittor/JittorLLMs#119]
环境信息：

**Comment by simonqian** [comment]
我这里也报了类似的错：
```bash
[i 0616 09:39:04.789768 88 compiler.py:955] Jittor(1.3.8.2) src: /home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor
[i 0616 09:39:04.790993 88 compiler.py:956] g++ at /usr/bin/g++(11.3.0)
[i 0616 09:39:04.791051 88 compiler.py:957] cache_path: /home/doudou/.cache/jittor/jt1.3.8/g++11.3.0/py3.8.16/Linux-4.15.0-1xbf/IntelRCoreTMi9xca/default
[i 0616 09:39:04.792763 88 __init__.py:411] Found nvcc(9.1.85) at /usr/bin/nvcc.
[i 0616 09:39:04.794241 88 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0616 09:39:04.867284 88 compiler.py:1010] cuda key:cu9.1.85_sm_86
In file included from /home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h: In lambda function:
/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:632:29: error: there are no arguments to ‘PyObject_CallOneArg’ that depend on a template parameter, so a declaration of ‘PyObject_CallOneArg’ must be available [-fpermissive]
  632 |             PyObjHolder ret(PyObject_CallOneArg(obj, args.obj));
      |                             ^~~~~~~~~~~~~~~~~~~
/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:632:29: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/doudou/projects/github/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/home/doudou/projects/github/JittorLLMs/models/util.py", line 33, in get_llama
    new_paths.append(download_fromhub(f"jittorhub://{f}", tdir="llama"))
  File "/home/doudou/projects/github/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/g++" "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/home/doudou/miniconda3/envs/jittor/lib/python3.8/site-packages/jittor/src" -I/home/doudou/miniconda3/envs/jittor/include/python3.8 -I/home/doudou/miniconda3/envs/jittor/include/python3.8  -O2   -o "/home/doudou/.cache/jittor/jt1.3.8/g++11.3.0/py3.8.16/Linux-4.15.0-1xbf/IntelRCoreTMi9xca/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so"
```

**Comment by hanhuili** [comment]
> Centos7环境信息： gcc 6.1.0 cuda 11.7 python 3.9
> 
> [i 0523 18:12:43.006756 44 jit_compiler.cc:28] Load cc_path: /home/aaa/anaconda3/envs/jjitor/bin/g++ terminate called after throwing an instance of 'std::runtime_error' what(): [f 0523 18:12:43.149831 44 helper_cuda.h:128] CUDA error at /home/aaa/anaconda3/envs/jjitor/lib/python3.9/site-packages/jittor/src/ops/array_op.cc:33 code=222( cudaErrorUnsupportedPtxVersion ) cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking) Aborted (core dumped)
> 
> 方便给出工程跑通的建议环境或者docker吗？

我也遇到这个问题了，老哥你怎么解决的

**Comment by tonylin52** [comment]
> > Centos7环境信息： gcc 6.1.0 cuda 11.7 python 3.9
> > [i 0523 18:12:43.006756 44 jit_compiler.cc:28] Load cc_path: /home/aaa/anaconda3/envs/jjitor/bin/g++ terminate called after throwing an instance of 'std::runtime_error' what(): [f 0523 18:12:43.149831 44 helper_cuda.h:128] CUDA error at /home/aaa/anaconda3/envs/jjitor/lib/python3.9/site-packages/jittor/src/ops/array_op.cc:33 code=222( cudaErrorUnsupportedPtxVersion ) cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking) Aborted (core dumped)
> > 方便给出工程跑通的建议环境或者docker吗？
> 
> 我也遇到这个问题了，老哥你怎么解决的

我直接放弃这个框架了。。因为所有的issus都没人维护。。这个工程太花屏了

**Comment by hanhuili** [comment]
> > > Centos7环境信息： gcc 6.1.0 cuda 11.7 python 3.9
> > > [i 0523 18:12:43.006756 44 jit_compiler.cc:28] Load cc_path: /home/aaa/anaconda3/envs/jjitor/bin/g++ terminate called after throwing an instance of 'std::runtime_error' what(): [f 0523 18:12:43.149831 44 helper_cuda.h:128] CUDA error at /home/aaa/anaconda3/envs/jjitor/lib/python3.9/site-packages/jittor/src/ops/array_op.cc:33 code=222( cudaErrorUnsupportedPtxVersion ) cudaStreamCreateWithFlags(&stream, cudaStreamNonBlocking) Aborted (core dumped)
> > > 方便给出工程跑通的建议环境或者docker吗？
> > 
> > 
> > 我也遇到这个问题了，老哥你怎么解决的
> 
> 我直接放弃这个框架了。。因为所有的issus都没人维护。。这个工程太花瓶了

唉，好的，谢谢老哥
