### ISSUE TITLE
用不了，安装一切正常，但跑不起来。

### ISSUE THREAD

**Issue by running-frog** [Jittor/JittorLLMs#125]
[i 0526 13:48:29.536000 24 compiler.py:955] Jittor(1.3.7.16) src: d:\personal\cfm\.virtualenvs\jittorllms-e--n4ezz\lib\site-packages\jittor
[i 0526 13:48:29.567000 24 compiler.py:956] cl at d:\personal\cfm\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0526 13:48:29.568000 24 compiler.py:957] cache_path: d:\personal\cfm\.cache\jittor\jt1.3.7\cl\py3.10.10\Windows-10-10.x02\AMDRyzen75800Hxb1\default
[i 0526 13:48:29.571000 24 install_cuda.py:93] cuda_driver_version: [12, 1, 0]
[i 0526 13:48:29.584000 24 __init__.py:411] Found d:\personal\cfm\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at d:\personal\cfm\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0526 13:48:29.615000 24 compiler.py:1010] cuda key:cu11.2.67
[i 0526 13:48:29.621000 24 __init__.py:227] Total mem: 13.86GB, using 4 procs for compiling.
[i 0526 13:48:31.356000 24 jit_compiler.cc:28] Load cc_path: d:\personal\cfm\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0526 13:48:31.356000 24 init.cc:62] Found cuda archs: [86,]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 8/8 [00:11<00:00,  1.38s/it]
[i 0526 13:48:45.554000 24 cuda_flags.cc:39] CUDA enabled.
Running on local URL:  http://0.0.0.0:51234

To create a public link, set `share=True` in `launch()`.

Compiling Operators(9/9) used: 16.1s eta:    0s

Compiling Operators(2/2) used: 6.22s eta:    0s

Compiling Operators(1/1) used: 3.07s eta:    0s
[w 0526 13:50:09.693000 56 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0526 13:50:09.694000 56 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:     4GB
 hold_vars: 417 lived_vars: 437 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used:   3.4GB(100%) unused: 1.317MB(0.0378%) total: 3.401GB
 name: sfrl is_device: 1 used:   512 B(0.0488%) unused:  1024KB(100%) total:     1MB
 name: sfrl is_device: 0 used:   512 B(0.0488%) unused:  1024KB(100%) total:     1MB
 name: sfrl is_device: 0 used: 9.401GB(73.4%) unused:   3.4GB(26.6%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu:  16.2GB gpu: 3.402GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================

[w 0526 13:50:09.855000 56 cuda_device_allocator.cc:30] Unable to alloc cuda device memory, use unify memory instead. This may cause low performance.
[i 0526 13:50:09.856000 56 cuda_device_allocator.cc:32]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:     4GB
 hold_vars: 417 lived_vars: 437 lived_ops: 135
 jtorch_grad_vars: 0
 name: sfrl is_device: 1 used:   3.4GB(100%) unused: 324.5KB(0.0091%) total:   3.4GB
 name: sfrl is_device: 1 used:   512 B(0.0488%) unused:  1024KB(100%) total:     1MB
 name: sfrl is_device: 0 used:   512 B(0.0488%) unused:  1024KB(100%) total:     1MB
 name: sfrl is_device: 0 used: 9.401GB(73.4%) unused:   3.4GB(26.6%) total:  12.8GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: temp is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu:  16.2GB gpu: 3.401GB cpu:  12.8GB
 free: cpu(    0 B) gpu(    0 B)
 swap: total(    0 B) last(    0 B)
===========================

Traceback (most recent call last):
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\blocks.py", line 1320, in process_api
    result = await self.call_function(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\blocks.py", line 1064, in call_function
    prediction = await utils.async_iteration(iterator)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\utils.py", line 514, in async_iteration
    return await iterator.__anext__()
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\utils.py", line 507, in __anext__
    return await anyio.to_thread.run_sync(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\gradio\utils.py", line 490, in run_sync_iterator_async
    return next(iterator)
  File "D:\software\JittorLLMs\web_demo.py", line 12, in predict
    for response, history in model.run_web_demo(input, history):
  File "D:\software\JittorLLMs\models\chatglm\__init__.py", line 42, in run_web_demo
    yield self.run(input_text, history=history)
  File "D:\software\JittorLLMs\models\chatglm\__init__.py", line 45, in run
    return self.model.chat(self.tokenizer, text, history=history)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jittor\__init__.py", line 118, in inner
    ret = func(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1233, in chat
    outputs = self.generate(**input_ids, **gen_kwargs)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jittor\__init__.py", line 118, in inner
    ret = func(*args, **kw)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\transformers\generation\utils.py", line 1437, in generate
    return self.sample(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\transformers\generation\utils.py", line 2443, in sample
    outputs = self(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1138, in forward
    transformer_outputs = self.transformer(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 973, in forward
    layer_ret = layer(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 614, in forward
    attention_outputs = self.attention(
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 454, in forward
    cos, sin = self.rotary_emb(q1, seq_len=position_ids.max() + 1)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "d:\personal\cfm/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 202, in forward
    t = torch.arange(seq_len, device=x.device, dtype=self.inv_freq.dtype)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jtorch\__init__.py", line 31, in inner
    ret = func(*args, **kw)
  File "d:\personal\cfm\.virtualenvs\JittorLLMs-E--n4ezZ\lib\site-packages\jittor\misc.py", line 809, in arange
    if isinstance(start, jt.Var): start = start.item()
RuntimeError: [f 0526 13:50:09.907000 56 executor.cc:682]
Execute fused operator(29/43) failed.
[JIT Source]: d:\personal\cfm\.cache\jittor\jt1.3.7\cl\py3.10.10\Windows-10-10.x02\AMDRyzen75800Hxb1\default\cu11.2.67\jit\__opkey0_broadcast_to__Tx_float16__DIM_3__BCAST_1__opkey1_broadcast_to__Tx_float16__DIM_3____hash_9730a00665a5a466_op.cc
[OP TYPE]: fused_op:( broadcast_to, broadcast_to, binary.multiply, reduce.add,)
[Input]: float16[12288,4096,]transformer.layers.6.attention.query_key_value.weight, float16[7,4096,],
[Output]: float16[7,12288,],
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: [f 0526 13:50:09.906000 56 helper_cuda.h:128] CUDA error at d:\personal\cfm\.virtualenvs\jittorllms-e--n4ezz\lib\site-packages\jittor\src\mem\allocator\cuda_device_allocator.cc:33  code=2( cudaErrorMemoryAllocation ) cudaMallocManaged(&ptr, size)

**Comment by zhoushiyoung** [comment]
一眼爆显存了，也有可能是内存
