### ISSUE TITLE
Mac M1  pro运行后错误如下 请大神指导，谢谢

### ISSUE THREAD

**Issue by lwo2002** [Jittor/JittorLLMs#128]
(jittor) lwo2002@AlexludeMacBook-Pro JittorLLMs % python web_demo.py chatglm
Traceback (most recent call last):
  File "/Users/lwo2002/JittorLLMs/web_demo.py", line 26, in <module>
    model = models.get_model(args)
  File "/Users/lwo2002/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/Users/lwo2002/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/Users/lwo2002/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/Users/lwo2002/miniforge3/envs/jittor/lib/python3.10/site-packages/jittor/__init__.py", line 13, in <module>
    from jittor_utils import lock
  File "/Users/lwo2002/miniforge3/envs/jittor/lib/python3.10/site-packages/jittor_utils/__init__.py", line 606, in <module>
    cc_path = env_or_find('cc_path', 'clang++', silent=True)
  File "/Users/lwo2002/miniforge3/envs/jittor/lib/python3.10/site-packages/jittor_utils/__init__.py", line 422, in env_or_find
    return find_exe(bname, silent=silent)
  File "/Users/lwo2002/miniforge3/envs/jittor/lib/python3.10/site-packages/jittor_utils/__init__.py", line 407, in find_exe
    version = get_version(name)
  File "/Users/lwo2002/miniforge3/envs/jittor/lib/python3.10/site-packages/jittor_utils/__init__.py", line 391, in get_version
    version = "("+v[-3]+")"
IndexError: list index out of range

**Comment by ZXiangQAQ** [comment]
终端里运行 clang++ --version，看看clang++的版本是多少，看起来像是获取版本号出错了

**Comment by msilemsile** [comment]
brew install libomp
