### ISSUE TITLE
centos7.5 python10 执行python3 cli_demo.py chatglm报错

### ISSUE THREAD

**Issue by zhaobingkun** [Jittor/JittorLLMs#140]
[root@localhost JittorLLMs]# python3 cli_demo.py chatglm
[i 0612 11:15:32.184341 64 compiler.py:955] Jittor(1.3.8.2) src: /usr/local/python3/lib/python3.10/site-packages/jittor
[i 0612 11:15:32.192548 64 compiler.py:956] g++ at /usr/bin/g++(4.8.5)
[i 0612 11:15:32.193299 64 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.8/g++4.8.5/py3.10.10/Linux-3.10.0-1xdb/IntelRCoreTMi5xe1/default
[i 0612 11:15:32.256082 64 __init__.py:411] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0612 11:15:32.263255 64 __init__.py:411] Found addr2line(2.27) at /usr/bin/addr2line.
g++: 错误：unrecognized command line option ‘-std=c++14’
Traceback (most recent call last):
  File "/soft/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/soft/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/soft/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/soft/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/usr/local/python3/lib/python3.10/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/usr/local/python3/lib/python3.10/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/usr/local/python3/lib/python3.10/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/usr/local/python3/lib/python3.10/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/usr/local/python3/lib/python3.10/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/usr/local/python3/lib/python3.10/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/usr/bin/g++" "/usr/local/python3/lib/python3.10/site-packages/jittor/src/utils/cache_compile.cc" "/usr/local/python3/lib/python3.10/site-packages/jittor/src/utils/log.cc" "/usr/local/python3/lib/python3.10/site-packages/jittor/src/utils/tracer.cc" "/usr/local/python3/lib/python3.10/site-packages/jittor/src/utils/jit_utils.cc" "/usr/local/python3/lib/python3.10/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/usr/local/python3/lib/python3.10/site-packages/jittor/src" -I/usr/local/include/python3.10 -I/usr/local/include/python3.10  -O2   -o "/root/.cache/jittor/jt1.3.8/g++4.8.5/py3.10.10/Linux-3.10.0-1xdb/IntelRCoreTMi5xe1/default/jit_utils_core.cpython-310-x86_64-linux-gnu.so"

**Comment by eeeeeio** [comment]
一样报这个错

**Comment by love01211** [comment]
这个我知道，是gcc版本不够导致的，升级到5.2.0就解决了
