### ISSUE TITLE
运行示例的时候报错，

### ISSUE THREAD

**Issue by cheng31869** [Jittor/JittorLLMs#146]
PS F:\JittorLLMs> python cli_demo.py chatglm
[i 0619 13:12:37.947000 88 compiler.py:955] Jittor(1.3.8.2) src: c:\users\31869\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0619 13:12:37.997000 88 compiler.py:956] cl at F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0619 13:12:37.998000 88 compiler.py:957] cache_path: F:\cache\.cache\jittor\jt1.3.8\cl\py3.10.11\Windows-10-10.xc3\AMDRyzen75800Hxb1\default
[i 0619 13:12:38.001000 88 install_cuda.py:93] cuda_driver_version: [12, 1, 0]
[i 0619 13:12:38.024000 88 __init__.py:411] Found F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0619 13:12:38.063000 88 compiler.py:1010] cuda key:cu11.2.67
[i 0619 13:12:38.064000 88 __init__.py:227] Total mem: 15.36GB, using 5 procs for compiling.
[i 0619 13:12:40.069000 88 jit_compiler.cc:28] Load cc_path: F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0619 13:12:40.069000 88 swap.cc:29] Load cpu_mem_limit: 3000000000
[i 0619 13:12:40.069000 88 swap.cc:30] Load device_mem_limit: 3000000000
[i 0619 13:12:40.076000 88 py_var_tracer.cc:22] Load trace_py_var: 3
[i 0619 13:12:40.076000 88 init.cc:62] Found cuda archs: [86,]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:06<00:45,  6.45s/it][e 0619 13:12:54.287000 88 mem_info.cc:101] appear time -> node cnt: {1:4469, }
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:10<01:15, 10.72s/it]
Traceback (most recent call last):
  File "F:\JittorLLMs\cli_demo.py", line 13, in <module>
    model = models.get_model(args)
  File "F:\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2812, in _load_pretrained_model
    error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 491, in _load_state_dict_into_model
    load(model_to_load, state_dict, prefix=start_prefix)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 485, in load
    module._load_from_state_dict(*args)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1348, in _load_from_state_dict
    self.load_state_dict(state)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py", line 104, in load_state_dict
    return super().load_state_dict(state_dict)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1339, in load_state_dict
    self.load_parameters(params)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1604, in load_parameters
    v.sync(False, False)
RuntimeError: [f 0619 13:12:54.287000 88 executor.cc:683]
Execute fused operator(3/5) failed.
[JIT Source]: F:\cache\.cache\jittor\jt1.3.8\cl\py3.10.11\Windows-10-10.xc3\AMDRyzen75800Hxb1\default\cu11.2.67\jit\__opkey0_reindex__Tx_float16__XDIM_1__YDIM_2__OVERFLOW_itof_0x0___INDEX0__e0_0____i0__e0_1___hash_31ae4cff793af536_op.cc
[OP TYPE]: fused_op:( reindex,)
[Input]: float16[67108864,], int32[2,],
[Output]: float16[16384,4096,],
[Async Backtrace]: ---
     F:\JittorLLMs\cli_demo.py:13 <<module>>
     F:\JittorLLMs\models\__init__.py:46 <get_model>
     F:\JittorLLMs\models\chatglm\__init__.py:48 <get_model>
     F:\JittorLLMs\models\chatglm\__init__.py:22 <__init__>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py:459 <from_pretrained>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py:2478 <from_pretrained>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py:2780 <_load_pretrained_model>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py:415 <load_state_dict>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py:228 <load>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py:1128 <load>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py:98 <safeunpickle>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py:270 <load_pytorch>
     C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py:87 <jittor_rebuild>
[Reason]: [f 0619 13:12:54.286000 88 swap.cc:40] Check failed: !x->flags.get(NodeFlags::_is_swapped)  Something wrong... Could you please report this issue?

**Comment by cheng31869** [comment]
参考了https://github.com/Jittor/JittorLLMs/issues/39 我在系统属性里面改了交换内存的大小上限为70000M，jittor_cache成功设置到充足的F盘。但错误不变。

**Comment by cheng31869** [comment]
设备名称	丞丞
处理器	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
机带 RAM	16.0 GB (15.4 GB 可用)

**Comment by cheng31869** [comment]
![image](https://github.com/Jittor/JittorLLMs/assets/117501212/7cc6ee39-4a7c-4159-b9e7-137fa8020d84)

**Comment by cheng31869** [comment]
不加$env:JT_SYNC=1的时候报错是这样的
PS F:\JittorLLMs> python cli_demo.py chatglm
[i 0619 13:43:40.706000 44 compiler.py:955] Jittor(1.3.8.2) src: c:\users\31869\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0619 13:43:40.751000 44 compiler.py:956] cl at F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0619 13:43:40.752000 44 compiler.py:957] cache_path: F:\cache\.cache\jittor\jt1.3.8\cl\py3.10.11\Windows-10-10.xc3\AMDRyzen75800Hxb1\default
[i 0619 13:43:40.755000 44 install_cuda.py:93] cuda_driver_version: [12, 1, 0]
[i 0619 13:43:40.779000 44 __init__.py:411] Found F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0619 13:43:40.816000 44 compiler.py:1010] cuda key:cu11.2.67
[i 0619 13:43:40.816000 44 __init__.py:227] Total mem: 15.36GB, using 5 procs for compiling.
Compiling jittor_core(151/151) used: 3.907s eta: 0.000s
[i 0619 13:43:54.180000 44 jit_compiler.cc:28] Load cc_path: F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0619 13:43:54.192000 44 init.cc:62] Found cuda archs: [86,]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  38%|█████████████████████▍                                   | 3/8 [00:21<00:36,  7.29s/it]
Traceback (most recent call last):
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py", line 228, in load
    return jt.load(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 44, in persistent_load
    load_tensor(contents, dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 21, in load_tensor
    loaded_storages[key] = contents.read_var(name, dtype)
RuntimeError: [f 0619 13:44:19.977000 44 executor.cc:683]
Execute fused operator(0/1) failed.[OP TYPE]: empty
[Input]:
[Output]: float16[67108864,],
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: [f 0619 13:44:19.971000 44 helper_cuda.h:128] CUDA error at c:\users\31869\appdata\local\programs\python\python310\lib\site-packages\jittor\src\mem\allocator\cuda_host_allocator.cc:22  code=2( cudaErrorMemoryAllocation ) cudaMallocHost(&ptr, size)
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\JittorLLMs\cli_demo.py", line 13, in <module>
    model = models.get_model(args)
  File "F:\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'F:\JittorLLMs\models\chatglm\pytorch_model-00004-of-00008.bin' at 'F:\JittorLLMs\models\chatglm\pytorch_model-00004-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by cheng31869** [comment]
$env:device_mem_limit="2000000000"这个对我来说并无作用，尽管他能读到这个配置，但是运行的时候交换显存就会爆掉，之后就报错了cudaErrorMemoryAllocation

**Comment by cheng31869** [comment]
而专用内存却没有多少使用的
![image](https://github.com/Jittor/JittorLLMs/assets/117501212/a8761008-9ae6-419f-8ad4-73c832603227)

**Comment by cheng31869** [comment]
改device_mem_limit没有用，改cpu_mem_limit的话如果大于交换显存了，就会报cudaErrorMemoryAllocation，小于的话，在交换显存没满的时候就报错someting worng
PS F:\JittorLLMs> python cli_demo.py chatglm
[i 0619 14:15:57.145000 24 compiler.py:955] Jittor(1.3.8.2) src: c:\users\31869\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0619 14:15:57.177000 24 compiler.py:956] cl at F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0619 14:15:57.177000 24 compiler.py:957] cache_path: F:\cache\.cache\jittor\jt1.3.8\cl\py3.10.11\Windows-10-10.xc3\AMDRyzen75800Hxb1\default
[i 0619 14:15:57.180000 24 install_cuda.py:93] cuda_driver_version: [12, 1, 0]
[i 0619 14:15:57.204000 24 __init__.py:411] Found F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at F:\cache\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0619 14:15:57.244000 24 compiler.py:1010] cuda key:cu11.2.67
[i 0619 14:15:57.246000 24 __init__.py:227] Total mem: 15.36GB, using 5 procs for compiling.
[i 0619 14:15:59.219000 24 jit_compiler.cc:28] Load cc_path: F:\cache\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0619 14:15:59.219000 24 swap.cc:29] Load cpu_mem_limit: 2000000000
[i 0619 14:15:59.219000 24 swap.cc:30] Load device_mem_limit: 2000000000
[i 0619 14:15:59.225000 24 init.cc:62] Found cuda archs: [86,]
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:06<00:47,  6.78s/it][i 0619 14:16:09.549000 24 ]
=== display_memory_info ===
 total_cpu_ram:    15 B total_device_ram:     4GB
 hold_vars: 369 lived_vars: 2394 lived_ops: 2369
 jtorch_grad_vars: 0
 name: sfrl is_device: 0 used: 1.773GB(100%) unused:     0 B(0%) total: 1.773GB
 name: sfrl is_device: 1 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: sfrl is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 name: sfrl is_device: 0 used:   594KB(0.0319%) unused: 1.774GB(100%) total: 1.774GB
 name: temp is_device: 0 used:     0 B(-nan(ind)%) unused:     0 B(-nan(ind)%) total:     0 B
 cpu&gpu: 3.548GB gpu:     0 B cpu: 3.548GB
 free: cpu(    0 B) gpu(2.701GB)
 swap: total(1.774GB) last(1.774GB)
===========================

Loading checkpoint shards:  12%|███████▏                                                 | 1/8 [00:06<00:47,  6.80s/it]
Traceback (most recent call last):
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py", line 228, in load
    return jt.load(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 270, in load_pytorch
    result = unpickler.load()
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 44, in persistent_load
    load_tensor(contents, dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 21, in load_tensor
    loaded_storages[key] = contents.read_var(name, dtype)
RuntimeError: [f 0619 14:16:09.549000 24 executor.cc:683]
Execute fused operator(0/1) failed.[OP TYPE]: empty
[Input]:
[Output]: float16[67108864,],
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: [f 0619 14:16:09.547000 24 swap.cc:99] Check failed: var->mem_ptr  Something wrong... Could you please report this issue?
 1 000001AC4415D2C0 (134217728,6485) 1
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\JittorLLMs\cli_demo.py", line 13, in <module>
    model = models.get_model(args)
  File "F:\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "F:\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\31869\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'F:\JittorLLMs\models\chatglm\pytorch_model-00002-of-00008.bin' at 'F:\JittorLLMs\models\chatglm\pytorch_model-00002-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
