### ISSUE TITLE
check_cuda     assert ret == 0 AssertionError

### ISSUE THREAD

**Issue by Savior1997** [Jittor/JittorLLMs#157]
[i 0707 10:59:05.145000 12 compiler.py:956] Jittor(1.3.8.5) src: c:\users\jun\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0707 10:59:05.187000 12 compiler.py:957] cl at C:\Users\Jun\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0707 10:59:05.187000 12 compiler.py:958] cache_path: C:\Users\Jun\.cache\jittor\jt1.3.8\cl\py3.10.11\Windows-10-10.x91\IntelRCeleronRx22\default
[i 0707 10:59:05.294000 12 __init__.py:411] Found nvcc(11.8.89) at C:\PROGRAM FILES\NVIDIA GPU COMPUTING TOOLKIT\CUDA\V11.8\BIN\nvcc.EXE.
[i 0707 10:59:05.988000 12 __init__.py:411] Found gdb(10.2) at C:\TDM-GCC-64\bin\gdb.EXE.
[i 0707 10:59:06.108000 12 __init__.py:411] Found addr2line(2.36.1) at C:\TDM-GCC-64\bin\addr2line.EXE.
[i 0707 10:59:06.159000 12 compiler.py:1011] cuda key:cu11.8.89
[i 0707 10:59:06.162000 12 __init__.py:227] Total mem: 15.85GB, using 5 procs for compiling.
Traceback (most recent call last):
  File "D:\AI\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "D:\AI\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "D:\AI\JittorLLMs\models\util.py", line 22, in get_chatrwkv
    return download_fromhub("jittorhub://RWKV-4-Pile-3B-EngChn-test4-20230115-fp32.pth", tdir="ChatRWKV")
  File "D:\AI\JittorLLMs\models\util.py", line 5, in download_fromhub
    import jittor as jt
  File "C:\Users\aa\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "C:\Users\aa\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 1195, in <module>
    check_cuda()
  File "C:\Users\aa\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 866, in check_cuda
    assert ret == 0
AssertionError

**Comment by Savior1997** [comment]
uninstall cuda

**Comment by linfx** [comment]
how ?
