### ISSUE TITLE
No module named 'torch.optim'

### ISSUE THREAD

**Issue by l15y** [Jittor/JittorLLMs#16]
具体环境在路径中可看到，项目是[https://github.com/l15y/wenda](https://github.com/l15y/wenda)
```
Traceback (most recent call last):
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\wenda\GLM6BAPI.py", line 144, in load_model
    model = AutoModel.from_pretrained(glm_path, local_files_only=True, trust_remote_code=True)
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\transformers\modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "C:\Users\cly/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 940, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "C:\Users\cly/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1277, in quantize
    self.transformer = quantize(self.transformer, bits, use_quantization_cache=use_quantization_cache, empty_init=empty_init, **kwargs)
  File "C:\Users\cly/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 437, in quantize
Traceback (most recent call last):
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\embeddings\huggingface.py", line 37, in __init__
    import sentence_transformers
    layer.attention.query_key_value = QuantizedLinearWithPara(
  File "C:\Users\cly/.cache\huggingface\modules\transformers_modules\local\quantization.py", line 293, in __init__
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\sentence_transformers\datasets\__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\sentence_transformers\datasets\ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\sentence_transformers\SentenceTransformer.py", line 15, in <module>
    from torch.optim import Optimizer
ModuleNotFoundError: No module named 'torch.optim'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\wenda\GLM6BAPI.py", line 152, in <module>
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_path)
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\langchain\embeddings\huggingface.py", line 41, in __init__
    raise ValueError(
    super(QuantizedLinear, self).__init__(*args, **kwargs)
ValueError: Could not import sentence_transformers python package. Please install it with `pip install sentence_transformers`.
  File "D:\WPy64-31090\python-3.10.9.amd64\lib\site-packages\jtorch\__init__.py", line 118, in __init__
    super().__init__(*args, **kw)
TypeError: Linear.__init__() got an unexpected keyword argument 'device'
```

**Comment by zjp-shadow** [comment]
你好，请问jtorch的版本是？

**Comment by l15y** [comment]
0.1.3，应该是最新的

**Comment by tfa2012** [comment]
我也碰到一样的问题

`
Using quantization cache
Applying quantization to glm layers
Traceback (most recent call last):
  File "/home/merlin/projects/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/merlin/projects/JittorLLMs/models/__init__.py", line 42, in get_model
    return module.get_model(args)
  File "/home/merlin/projects/JittorLLMs/models/chatglm/__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "/home/merlin/projects/JittorLLMs/models/chatglm/__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "/home/merlin/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "/home/merlin/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2362, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/merlin/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 941, in __init__
    self.quantize(self.config.quantization_bit, self.config.quantization_embeddings, use_quantization_cache=True, empty_init=True)
  File "/home/merlin/.cache/huggingface/modules/transformers_modules/local/modeling_chatglm.py", line 1291, in quantize
    self.transformer = quantize(self.transformer, bits, use_quantization_cache=use_quantization_cache, empty_init=empty_init, **kwargs)
  File "/home/merlin/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 444, in quantize
    layer.attention.query_key_value = QuantizedLinearWithPara(
  File "/home/merlin/.cache/huggingface/modules/transformers_modules/local/quantization.py", line 297, in __init__
    super(QuantizedLinear, self).__init__(*args, **kwargs)
  File "/home/merlin/.local/lib/python3.10/site-packages/jtorch/__init__.py", line 118, in __init__
    super().__init__(*args, **kw)
TypeError: Linear.__init__() got an unexpected keyword argument 'device'
`
