### ISSUE TITLE
报错： in check_cuda     assert ret == 0 AssertionError 

### ISSUE THREAD

**Issue by linfx** [Jittor/JittorLLMs#163]
PS D:\samples\llm\JittorLLMs> python cli_demo.py chatrwkv 
[i 0814 09:11:50.124000 64 compiler.py:956] Jittor(1.3.8.5) src: c:\users\aaa\appdata\local\programs\python\python310\lib\site-packages\jittor
[i 0814 09:11:50.153000 64 compiler.py:957] cl at C:\Users\AAA\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0814 09:11:50.154000 64 compiler.py:958] cache_path: C:\Users\AAA\.cache\jittor\jt1.3.8\cl\py3.10.1\Windows-10-10.x86\IntelRCoreTMi7x93\default
[i 0814 09:11:50.157000 64 install_cuda.py:93] cuda_driver_version: [10, 1, 0]
[i 0814 09:11:50.184000 64 __init__.py:411] Found C:\Users\AAA\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe(10.2.89) at C:\Users\AAA\.cache\jittor\jtcuda\cuda10.2_cudnn7_win\bin\nvcc.exe.
[i 0814 09:11:50.337000 64 compiler.py:1011] cuda key:cu10.2.89
[i 0814 09:11:50.339000 64 __init__.py:227] Total mem: 15.91GB, using 5 procs for compiling.
Traceback (most recent call last):
  File "D:\samples\llm\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "D:\samples\llm\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "D:\samples\llm\JittorLLMs\models\util.py", line 22, in get_chatrwkv
    return download_fromhub("jittorhub://RWKV-4-Pile-3B-EngChn-test4-20230115-fp32.pth", tdir="ChatRWKV")
  File "D:\samples\llm\JittorLLMs\models\util.py", line 5, in download_fromhub
    import jittor as jt
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 1195, in <module>
    check_cuda()
  File "C:\Users\AAA\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 866, in check_cuda
    assert ret == 0
AssertionError

**Comment by fi5ee** [comment]
没装cuda?

**Comment by AbyssGio** [comment]
您好，请问您解决这个问题了吗？
