### ISSUE TITLE
安装很费劲，现在遇到如下问题，有人能帮我看看嘛

### ISSUE THREAD

**Issue by trifolium-wang** [Jittor/JittorLLMs#164]
安装环境
CentOS 7
python 3.8， 安装后发现python-configure找不到，重新软连接
启动，发现找不到g++
安装了gcc g++，然后发现版本太低，换成了7.3.1-5
然后发现还是不行，报错如下：
```
[root@localhost JittorLLMs]# python cli_demo.py chatglm[i 0814 19:21:24.608756 68 compiler.py:956] Jittor(1.3.8.5) src: /usr/local/python3/lib/python3.8/site-packages/jittor[i 0814 19:21:24.611043 68 compiler.py:957] g++ at /opt/rh/devtoolset-7/root/usr/bin/g++(7.3.1)[i 0814 19:21:24.611129 68 compiler.py:958] cache_path: /root/.cache/jittor/jt1.3.8/g++7.3.1/py3.8.3/Linux-3.10.0-1x20/IntelRCoreTMi5xe5/default[i 0814 19:21:24.615340 68 __init__.py:411] Found addr2line(2.28) at /opt/rh/devtoolset-7/root/usr/bin/addr2line.
In file included from /usr/local/python3/lib/python3.8/site-packages/jittor/src/pyjt/py_converter.h:11:0,
                 from /usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc:8:
/usr/local/python3/lib/python3.8/site-packages/jittor/src/pyjt/py_obj_holder.h:8:10: fatal error: Python.h: 没有那个文件或目录
 #include <Python.h>
          ^~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/root/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/root/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/root/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/usr/local/python3/lib/python3.8/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/usr/local/python3/lib/python3.8/site-packages/jittor/compiler.py", line 1190, in <module>
    check_cache_compile()
  File "/usr/local/python3/lib/python3.8/site-packages/jittor/compiler.py", line 885, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/usr/local/python3/lib/python3.8/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/usr/local/python3/lib/python3.8/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/usr/local/python3/lib/python3.8/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/opt/rh/devtoolset-7/root/usr/bin/g++" "/usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/cache_compile.cc" "/usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/log.cc" "/usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/tracer.cc" "/usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/jit_utils.cc" "/usr/local/python3/lib/python3.8/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/usr/local/python3/lib/python3.8/site-packages/jittor/src" -I/usr/local/include/python3.8 -I/usr/local/include/python3.8  -O2   -o "/root/.cache/jittor/jt1.3.8/g++7.3.1/py3.8.3/Linux-3.10.0-1x20/IntelRCoreTMi5xe5/default/jit_utils_core.cpython-38-x86_64-linux-gnu.so"
```

**Comment by trifolium-wang** [comment]
还得是ubuntu ，centos 实在没办法装，各种问题，ubuntu 就好多了。
