### ISSUE TITLE
windows系统下用wsl2部署该项目

### ISSUE THREAD

**Issue by venxzw** [Jittor/JittorLLMs#169]
环境：python=3.8，jittor=1.3.7.10，jtorch=0.1.7，在按照readme安装完后运行下列命令：
export JT_SYNC=1
export trace_py_var=3
export JT_SAVE_MEM=1
export cpu_mem_limit=10000000000
export device_mem_limit=8000000000
conda activate jittorllm
cd JittorLLMs/
python cli_demo.py chatglm
然后出现如下问题：
[i 1015 22:19:39.834705 92 __init__.py:227] Total mem: 12.35GB, using 4 procs for compiling.
/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/site-packages/jittor/src/mem/swap.cc:24:19: error: ‘getpid’ was not declared in this scope; did you mean ‘get_tid’?
   24 | static int _pid = getpid();
      |                   ^~~~~~
      |                   get_tid
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/site-packages/jittor_utils/__init__.py", line 197, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 1015 22:20:10.876637 92 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/usr/bin/g++" "/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/site-packages/jittor/src/mem/swap.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always   -I"/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/site-packages/jittor/src" -I/home/cynicism/miniconda3/envs/jittorllm/include/python3.8 -I/home/cynicism/miniconda3/envs/jittorllm/include/python3.8 -DHAS_CUDA -DIS_CUDA -I"/home/cynicism/JittorLLMs/F:/jittorllms/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/home/cynicism/miniconda3/envs/jittorllm/lib/python3.8/site-packages/jittor/extern/cuda/inc"   -I"/home/cynicism/JittorLLMs/F:/jittorllms/.cache/jittor/jt1.3.7/g++9.4.0/py3.8.16/Linux-5.10.16.x5a/11thGenIntelRCx72/default/cu11.2.152"   -O2   -c -DJT_SAVE_MEM=1 -o "/home/cynicism/JittorLLMs/F:/jittorllms/.cache/jittor/jt1.3.7/g++9.4.0/py3.8.16/Linux-5.10.16.x5a/11thGenIntelRCx72/default/cu11.2.152/obj_files/swap.cc.o"
请问各位大佬，能通过什么办法解决呢

**Comment by ankrwu** [comment]
gcc g++ 版本不能太新，你换个10试试
