### ISSUE TITLE
在最后一步python cli_demo.py报错求助

### ISSUE THREAD

**Issue by liutianye** [Jittor/JittorLLMs#170]
Building wheels for collected packages: jtorch, torch, torchvision
  Building wheel for jtorch (setup.py) ... done
  Created wheel for jtorch: filename=jtorch-0.1.7-py3-none-any.whl size=52207 sha256=0dcf8be047ce00a1b4878ec767167e0c54f279606b4350c5ec4c00c820cdb647
  Stored in directory: c:\users\liuti\appdata\local\pip\cache\wheels\86\6e\e8\ee25ca9857bb3b1d6a7fd285dc3b88492e65df5e76ffc4507e
  Building wheel for torch (setup.py) ... done
  Created wheel for torch: filename=torch-2.0.0-py3-none-any.whl size=1002 sha256=87a5042a9d0716ec5d5b77e4a8b219a2717a57210d8aae8ae473298345b61359
  Stored in directory: c:\users\liuti\appdata\local\pip\cache\wheels\c3\84\05\c36627f1034fea71700429c61b9c1263e953ae11d11f5796fb
  Building wheel for torchvision (setup.py) ... done
  Created wheel for torchvision: filename=torchvision-0.15-py3-none-any.whl size=1052 sha256=d02c560a8fa58b5e159fe18d35de69d0cffe85ffb47b1a2fd7dd7a0ef3441fac
  Stored in directory: c:\users\liuti\appdata\local\pip\cache\wheels\34\3f\c1\1e8cd03e409522239b1f87492bd57726ea5dcc8d27af98ecb7
Successfully built jtorch torch torchvision
Installing collected packages: pywin32, wheel, urllib3, six, pillow, numpy, idna, colorama, charset-normalizer, certifi, tqdm, requests, astunparse, jittor, jtorch, torchvision, torch
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0+cu118, but you have torch 2.0.0 which is incompatible.
Successfully installed astunparse-1.6.3 certifi-2023.7.22 charset-normalizer-2.0.4 colorama-0.4.6 idna-3.4 jittor-1.3.8.5 jtorch-0.1.7 numpy-1.26.1 pillow-10.1.0 pywin32-305.1 requests-2.31.0 six-1.16.0 torch-2.0.0 torchvision-0.15 tqdm-4.65.0 urllib3-1.26.16 wheel-0.41.2

E:\jittorLLMs\JittorLLMs>python cli_demo.py [chatglm|pangualpha|llama|chatrwkv|llama2|atom7b]
'pangualpha' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

前面命令都执行了，最后这一步的时候，提示了这个error消息，这该怎么处理呢？

**Comment by Qqgl** [comment]
最后一步执行我是这样的： python cli_demo.py chatglm 
[chatglm|pangualpha|llama|chatrwkv|llama2|atom7b] 这里面是让你选吧？  。。。

**Comment by Qqgl** [comment]
但是我也报错了：
Traceback (most recent call last):
  File "F:\AI\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "F:\AI\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "F:\AI\JittorLLMs\models\util.py", line 64, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "F:\AI\JittorLLMs\models\util.py", line 5, in download_fromhub
    import jittor as jt
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\jittor\compiler.py", line 1361, in <module>
    import jittor_core as core
ImportError: DLL load failed while importing jittor_core: 找不到指定的模块。

**Comment by fi5ee** [comment]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0+cu118 requires torch==2.1.0+cu118, but you have torch 2.0.0 which is incompatible.
这一句是说你需要先安装torch==2.1.0+cu118
E:\jittorLLMs\JittorLLMs>python cli_demo.py [chatglm|pangualpha|llama|chatrwkv|llama2|atom7b]
这里把[chatglm|pangualpha|llama|chatrwkv|llama2|atom7b]改成你需要的模型，不加方括号
