### ISSUE TITLE
最后在执行python cli_demo.py chatglm时报错了（哪位大佬看看呀）

### ISSUE THREAD

**Issue by Qqgl** [Jittor/JittorLLMs#171]
[i 1027 17:59:32.642350 68 lock.py:85] Create lock file:C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\jittor.lock
[i 1027 17:59:32.656415 68 install_msvc.py:8] Installing MSVC...
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/msvc.zip to C:\Users\asus\.cache\jittor\msvc\msvc.zip
53.3MB [01:50, 504kB/s]
[i 1027 18:01:25.686635 68 compiler.py:956] Jittor(1.3.8.5) src: c:\users\asus\appdata\local\programs\python\python39\lib\site-packages\jittor
[i 1027 18:01:25.917320 68 compiler.py:957] cl at C:\Users\asus\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 1027 18:01:25.918358 68 compiler.py:958] cache_path: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default
[i 1027 18:01:25.959133 68 install_cuda.py:93] cuda_driver_version: [9, 1, 0]
[w 1027 18:01:25.960004 68 install_cuda.py:114] Unsupport cuda driver version: [9, 1, 0], at least 10.2
[i 1027 18:01:25.969528 68 install_cuda.py:93] cuda_driver_version: [9, 1, 0]
[w 1027 18:01:25.970369 68 install_cuda.py:114] Unsupport cuda driver version: [9, 1, 0], at least 10.2
[i 1027 18:01:25.989251 68 compiler.py:34] Create cache dir: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default\jit
[i 1027 18:01:25.989943 68 compiler.py:34] Create cache dir: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default\obj_files
[i 1027 18:01:25.990633 68 compiler.py:34] Create cache dir: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default\gen
[i 1027 18:01:25.993273 68 compiler.py:34] Create cache dir: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default\tmp
[i 1027 18:01:25.993713 68 compiler.py:34] Create cache dir: C:\Users\asus\.cache\jittor\jt1.3.8\cl\py3.9.13\Windows-10-10.x2b\IntelRCoreTMi5x78\default\checkpoints
[i 1027 18:01:25.995751 68 __init__.py:227] Total mem: 3.89GB, using 1 procs for compiling.
Compiling jit_utils_core(5/5) used: 14.811s eta: 0.000s
Compiling jit_utils_core(5/5) used: 9.361s eta: 0.000ss
Compiling jittor_core(150/150) used: 239.008s eta: 0.000ss
Traceback (most recent call last):
  File "F:\AI\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "F:\AI\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "F:\AI\JittorLLMs\models\util.py", line 64, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "F:\AI\JittorLLMs\models\util.py", line 5, in download_fromhub
    import jittor as jt
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\jittor\__init__.py", line 18, in <module>
    from . import compiler
  File "C:\Users\asus\AppData\Local\Programs\Python\Python39\lib\site-packages\jittor\compiler.py", line 1361, in <module>
    import jittor_core as core
ImportError: DLL load failed while importing jittor_core: 找不到指定的模块。

**Comment by knightc2020** [comment]
我安装pangualpha的时候，也报这个错误“import jittor_core as core ImportError: DLL load failed while importing jittor_core: 找不到指定的模块。”
