### ISSUE TITLE
python cli_demo.py chatglm执行之后，输入用户之后报错，没有了后续结果

### ISSUE THREAD

**Issue by Qqgl** [Jittor/JittorLLMs#173]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:59<00:00,  7.44s/it]
用户输入:zhangsan
raise_cxx_exception 3221225477
Traceback (most recent call last):
  File "D:\software\AISoft\JittorLLMs\cli_demo.py", line 9, in <module>
    model.chat()
  File "D:\software\AISoft\JittorLLMs\models\chatglm\__init__.py", line 36, in chat
    for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
  File "C:\Users\qiuguolong/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1259, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "C:\Users\qiuguolong/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1334, in stream_generate
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\qiuguolong/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1083, in prepare_inputs_for_generation
    mask_token = MASK if MASK in input_ids else gMASK
                         ^^^^^^^^^^^^^^^^^
  File "D:\software\AISoft\JittorLLMs\venv\Lib\site-packages\jittor\misc.py", line 132, in __contains__
    return bool((x == key).any())
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\software\AISoft\JittorLLMs\venv\Lib\site-packages\jittor\__init__.py", line 2026, in to_bool
    return ori_bool(v.item())
                    ^^^^^^^^
RuntimeError: [f 1101 22:27:32.528000 36 executor.cc:686] 
Execute fused operator(0/258) failed.
[JIT Source]: D:\software\AISoft\llm\.cache\jittor\jt1.3.8\cl\py3.11.5\Windows-10-10.x6a\AMDRyzen536006x1a\main\jit\__opkey0_unary__Tx_float16__Ty_float32__OP_cast__JIT_1__JIT_cpu_1__graph_010000___var_info___hash_e8d5f58a3e108a
25_op.cc
[OP TYPE]: fused_op:( unary.cast,)
[Input]: float16[150528,4096,],
[Output]: float32[150528,4096,]transformer.word_embeddings.weight,
[Async Backtrace]: not found, please set env JT_SYNC=1, trace_py_var=3
[Reason]: exception: access violation writing 0000000000000000
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3

set JT_SYNC=1
set trace_py_var=3
均已执行，但是一样的错误！

**Comment by youngcraft** [comment]
Windows下用不了，换成ubuntu就可以了

**Comment by Qqgl** [comment]
got it!
