### ISSUE TITLE
无法启动web_demo.py & cli_demo.py 报错“import torch.utils.hooks as hooks ModuleNotFoundError: No module named 'torch.utils.hooks'”

### ISSUE THREAD

**Issue by Twiyin0** [Jittor/JittorLLMs#189]
# 环境
windows server 2022
python 3.11.0
pip 24.0
CPU: R5 2600
GPU: GTX1660 super 6G
CUDA: 12.4

以来安装步骤都依照README.md执行，chatglm模型已下载完成checkpoints通过
但是在运行
```python
python web_demo.py chatglm
```
后报错
Traceback (most recent call last):
  File "H:\Prject\Chatglm\JittorLLMs\models\__init__.py", line 49, in get_model
    return module.get_model(args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Prject\Chatglm\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
           ^^^^^^^^^^^^^^^^^^
  File "H:\Prject\Chatglm\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ENV\python\Lib\site-packages\transformers\models\auto\auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ENV\python\Lib\site-packages\transformers\dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ENV\python\Lib\site-packages\transformers\dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ENV\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 28, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "F:\ENV\python\Lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "F:\ENV\python\Lib\site-packages\accelerate\__init__.py", line 16, in <module>
    from .accelerator import Accelerator
  File "F:\ENV\python\Lib\site-packages\accelerate\accelerator.py", line 33, in <module>
    import torch.utils.hooks as hooks
ModuleNotFoundError: No module named 'torch.utils.hooks'
Import Error, maybe the dependencies are not installed, please try 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'
导入错误，可能没有安装此模型需要的依赖，请尝试运行 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'
按照log提示，已将chatglm下的requirements.txt内依赖全部安装完成，但是再次运行还是会报这个错误，尝试过重来，依旧如此。
  
完整日志文件请看[完整日志](https://paste.iin0.cn/?95166ebbbb3dee6d#BoGK4NPYuQszX4F7JCJy2jqoCo1KrcWQgqrAwfLNufH5)

**Comment by Twiyin0** [comment]
已解决，卸载accelerate依赖就可以了
