### ISSUE TITLE
No module named 'torch.utils.hooks'

### ISSUE THREAD

**Issue by chalecao** [Jittor/JittorLLMs#19]
ModuleNotFoundError: No module named 'torch.utils.hooks'

**Comment by cjld** [comment]
您是再用jtorch跑什么模型呢

**Comment by dofish** [comment]
我也是装完jittor版的torch，等他编译完，就没有hooks
跑chatglm的时候就报这个错

Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
[i 0406 23:15:40.028468 60 lock.py:85] Create lock file:/root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/jittor.lock
[i 0406 23:15:40.039808 60 compiler.py:955] Jittor(1.3.7.12) src: /usr/local/lib/python3.7/dist-packages/jittor
[i 0406 23:15:40.042714 60 compiler.py:956] g++ at /usr/bin/g++(7.5.0)
[i 0406 23:15:40.042853 60 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default
[i 0406 23:15:40.046273 60 __init__.py:411] Found nvcc(10.2.89) at /usr/local/cuda/bin/nvcc.
[i 0406 23:15:40.049204 60 __init__.py:411] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0406 23:15:40.167546 60 compiler.py:1010] cuda key:cu10.2.89_sm_60_75
[i 0406 23:15:40.191754 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75
[i 0406 23:15:40.191962 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/jit
[i 0406 23:15:40.192088 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/obj_files
[i 0406 23:15:40.192209 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/gen
[i 0406 23:15:40.192325 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/tmp
[i 0406 23:15:40.192439 60 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/checkpoints
[i 0406 23:15:53.227090 36 __init__.py:227] Total mem: 31.28GB, using 10 procs for compiling.
Compiling jittor_core(151/151) used: 26.367s eta: 0.000s
[i 0406 23:16:19.839595 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0406 23:16:19.929955 36 init.cc:62] Found cuda archs: [60,75,]
[i 0406 23:16:19.983571 36 __init__.py:411] Found mpicc(2.1.1) at /usr/bin/mpicc.
[i 0406 23:16:20.011883 36 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/custom_ops
[i 0406 23:16:21.547675 36 compile_extern.py:339] Downloading cutt...
Downloading https://codeload.github.com/Jittor/cutt/zip/v1.2 to /root/.cache/jittor/cutt/cutt-1.2.zip
200kB [00:01, 622kB/s] [i 0406 23:16:22.825233 36 compile_extern.py:352] installing cutt...
Compiling libcutt(9/9) used: 10.855s eta: 0.000s
296kB [00:12, 24.8kB/s]
[i 0406 23:16:34.786003 36 compile_extern.py:73] Downloading mkl...
Downloading https://cg.cs.tsinghua.edu.cn/jittor/assets/dnnl_lnx_2.2.0_cpu_gomp.tgz to /root/.cache/jittor/mkl/dnnl_lnx_2.2.0_cpu_gomp.tgz
 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 10.1M/10.5M [00:06<00:00, 11.5MB/s]Use time: 13.56 ms per iteration.
Example passed on CPU.
[i 0406 23:16:46.700373 36 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++7.5.0/py3.7.5/Linux-5.15.77-x81/AMDRyzen53500Xx19/default/cu10.2.89_sm_60_75/cuda
10.5MB [00:16, 11.5MB/s]                                                                                                                                                         Compiling gen_ops_cudnn_conv_backward_x_cudnn_conv_backward____hash887802(16/16) used: 3.441s eta: 0.000s
10.5MB [00:22, 495kB/s] 


>>> dir(torch.utils)
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_flatten_dense_tensors', '_unflatten_dense_tensors', 'checkpoint', 'cpp_extension', 'data', 'dtype']

>>> torch.__version__
'2.0.0'
>>> torch.cuda.is_available()
1
>>>

**Comment by poo0054** [comment]
运行
> python web_demo.py chatglm

```
Traceback (most recent call last):
  File "D:\project\gpt\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "D:\project\gpt\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "D:\project\gpt\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 455, in from_pretrained
    model_class = get_class_from_dynamic_module(
  File "C:\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 374, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 147, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\poo00/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 28, in <module>
    from transformers.modeling_utils import PreTrainedModel
  File "C:\Python310\lib\site-packages\transformers\modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "C:\Python310\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "C:\Python310\lib\site-packages\accelerate\accelerator.py", line 29, in <module>
    import torch.utils.hooks as hooks
ModuleNotFoundError: No module named 'torch.utils.hooks'
Import Error, maybe the dependencies are not installed, please try 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'
导入错误，可能没有安装此模型需要的依赖，请尝试运行 'python -m pip install -r models/chatglm/requirements.txt -i https://pypi.jittor.org/simple'
```

我也有这个

**Comment by feiyuntaoist** [comment]
pip uninstall accelerate

**Comment by haiwen-yang** [comment]
accelerate卸载到到是能跑了，但是模型回答不出东西来，不知道是不是因为卸载了它的原因。
