### ISSUE TITLE
Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by WSitong** [Jittor/JittorLLMs#193]
按照指导装完所有依赖了，运行ppython cli_demo.py chatglm报错，这是什么问题

Loading checkpoint shards:  50%|██████████▌          | 4/8 [00:12<00:12,  3.19s/it]
Traceback (most recent call last):
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/jtorch/__init__.py", line 251, in load
    return jt.load(path)
           ^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/jittor/__init__.py", line 1128, in load
    model_dict = safeunpickle(path)
                 ^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/jittor/__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
                 ^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/jittor_utils/load_pytorch.py", line 279, in load_pytorch
    magic_number = pickle.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: A load persistent id instruction was encountered,
but no persistent_load function was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
       ^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/apps/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/models/__init__.py", line 49, in get_model
    return module.get_model(args)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/models/chatglm/__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
           ^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/models/chatglm/__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/apps/JittorLLMs/venv/lib/python3.11/site-packages/transformers/modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for '/root/apps/JittorLLMs/models/chatglm/pytorch_model-00005-of-00008.bin' at '/root/apps/JittorLLMs/models/chatglm/pytorch_model-00005-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by WSitong** [comment]
删除/root/apps/JittorLLMs/models/chatglm/pytorch_model-00005-of-00008.bin后正常
