### ISSUE TITLE
OSError: [WinError 1314] 客户端没有所需的特权

### ISSUE THREAD

**Issue by forestttree** [Jittor/JittorLLMs#27]
D:\JittorLLMs>python cli_demo.py chatglm
[i 0406 21:04:11.694000 84 compiler.py:955] Jittor(1.3.7.12) src: d:\python\python311\lib\site-packages\jittor
[i 0406 21:04:11.728000 84 compiler.py:956] cl at C:\Users\XXXX\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0406 21:04:11.728000 84 compiler.py:957] cache_path: C:\Users\XXXX\.cache\jittor\jt1.3.7\cl\py3.11.3\Windows-10-10.x06\AMD\default
[i 0406 21:04:11.761000 84 __init__.py:227] Total mem: 31.96GB, using 10 procs for compiling.
[i 0406 21:04:13.000000 84 jit_compiler.cc:28] Load cc_path: C:\Users\XXXX\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0406 21:04:13.144000 84 compile_extern.py:522] mpicc not found, distribution disabled.
Traceback (most recent call last):
  File "D:\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\JittorLLMs\models\__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "D:\JittorLLMs\models\util.py", line 54, in get_chatglm
    os.symlink(new_path[-1], os.path.join(ln_dir, f))
OSError: [WinError 1314] 客户端没有所需的特权。: 'C:\\Users\\XXXX\\.cache\\jittor\\jt1.3.7\\cl\\py3.11.3\\Windows-10-10.x06\\AMD\\default\\checkpoints\\chat-glm/pytorch_model-00005-of-00008.bin' -> 'D:\\JittorLLMs\\models\\chatglm\\pytorch_model-00005-of-00008.bin'

手动复制每一个下载的bin文件 C: -> D: 可以继续

**Comment by zjp-shadow** [comment]
可以尝试使用管理员权限的终端运行该命令
