### ISSUE TITLE
compile operators failed

### ISSUE THREAD

**Issue by taskmgr** [Jittor/JittorLLMs#29]
webui and cli can start,but when input text and infer the jittor will compile operators and fail.
GPU RTX3060 laptop 6G/ CPU R7 5800H/Windows 11/16G ram
Here're the output:

Compiling Operators(14/14) used: 4.21s eta:    0s
[e 0407 01:20:46.873000 72 log.cc:565] cl : Command line warning D9025 : overriding '/EHa' with '/EHs'
code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.cc
E:\program_files\anaconda\include\cuda\std\detail/libcxx/include/type_traits(4842): error: identifier "__builtin_is_constant_evaluated" is undefined

E:\program_files\anaconda\include\cuda\std\detail/libcxx/include/type_traits(4847): error: identifier "__builtin_is_constant_evaluated" is undefined

2 errors detected in the compilation of "C:/Users/username/.cache/jittor/jt1.3.7/cl/py3.10.9/Windows-10-10.x13/AMDRyzen75800Hxb1/main/cu11.2.67/jit/code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.cc".
code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.cc

Traceback (most recent call last):
  File "E:\SAM_model\jittor\JittorLLMs\cli_demo.py", line 9, in <module>
    model.chat()
  File "E:\SAM_model\jittor\JittorLLMs\models\chatglm\__init__.py", line 36, in chat
    for response, history in self.model.stream_chat(self.tokenizer, text, history=history):
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1259, in stream_chat
    for outputs in self.stream_generate(**input_ids, **gen_kwargs):
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1336, in stream_generate
    outputs = self(
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 1138, in forward
    transformer_outputs = self.transformer(
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 973, in forward
    layer_ret = layer(
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 614, in forward
    attention_outputs = self.attention(
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 454, in forward
    cos, sin = self.rotary_emb(q1, seq_len=position_ids.max() + 1)
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\nn\__init__.py", line 16, in __call__
    return self.forward(*args, **kw)
  File "C:\Users\username/.cache\huggingface\modules\transformers_modules\local\modeling_chatglm.py", line 202, in forward
    t = torch.arange(seq_len, device=x.device, dtype=self.inv_freq.dtype)
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jtorch\__init__.py", line 31, in inner
    ret = func(*args, **kw)
  File "E:\SAM_model\jittor\JittorLLMs\venv\lib\site-packages\jittor\misc.py", line 809, in arange
    if isinstance(start, jt.Var): start = start.item()
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.item)).

Types of your inputs are:
 self   = Var,
 args   = (),

The function declarations are:
 ItemData item()

Failed reason:[f 0407 01:20:46.875000 72 parallel_compiler.cc:330] Error happend during compilation:
 [Error] source file location:C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main\cu11.2.67\jit\code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.cc
Compile operator(1/7)failed:Op(12536:0:1:1:i1:o1:s0,code->12537)

Reason: [f 0407 01:20:46.873000 72 log.cc:608] Check failed ret(1) == 0(0) Run cmd failed: "C:\Users\username\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe" "C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main\cu11.2.67\jit\code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.cc"            -shared  -L"E:\program_files\anaconda\libs" -lpython310  -Xcompiler -EHa -Xcompiler -MD -Xcompiler -utf-8   -I"C:\Users\username\.cache\jittor\msvc\VC\include" -I"C:\Users\username\.cache\jittor\msvc\win10_kits\include\ucrt" -I"C:\Users\username\.cache\jittor\msvc\win10_kits\include\shared" -I"C:\Users\username\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX  -L"C:\Users\username\.cache\jittor\msvc\VC\lib" -L"C:\Users\username\.cache\jittor\msvc\win10_kits\lib\um\x64" -L"C:\Users\username\.cache\jittor\msvc\win10_kits\lib\ucrt\x64"  -I"e:\sam_model\jittor\jittorllms\venv\lib\site-packages\jittor\src" -I"E:\program_files\anaconda\include" -DHAS_CUDA -DIS_CUDA -I"C:\Users\username\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"e:\sam_model\jittor\jittorllms\venv\lib\site-packages\jittor\extern\cuda\inc"  -lcudart -L"C:\Users\username\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\lib\x64" -L"C:\Users\username\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin"  -I"C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main\cu11.2.67" -L"C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main\cu11.2.67" -L"C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main"  -l"jit_utils_core.cp310-win_amd64"  -l"jittor_core.cp310-win_amd64"  -x cu --cudart=shared -ccbin="C:\Users\username\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" --use_fast_math  -w  -I"e:\sam_model\jittor\jittorllms\venv\lib\site-packages\jittor\extern/cuda/inc"  -arch=compute_86  -code=sm_86  -o "C:\Users\username\.cache\jittor\jt1.3.7\cl\py3.10.9\Windows-10-10.x13\AMDRyzen75800Hxb1\main\cu11.2.67\jit\code__IN_SIZE_1__in0_dim_4__in0_type_float32__OUT_SIZE_1__out0_dim_4__out0_type_float32__H___hash_3febe3994cb3e308_op.dll" -Xlinker -EXPORT:"?jit_run@CodeOp@jittor@@QEAAXXZ"

**Comment by cjld** [comment]
could you please provide the full log, from the command start
