### ISSUE TITLE
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync)).

### ISSUE THREAD

**Issue by qinxiandiqi** [Jittor/JittorLLMs#34]
请问启动web_demo.py chatglm一直报这个错是怎么回事呢？

(jittor) D:\Jianan\Develop\github\JittorLLMs>python web_demo.py chatglm
[i 0407 16:09:30.146000 88 compiler.py:955] Jittor(1.3.7.12) src: d:\jianan\win\anaconda3\envs\jittor\lib\site-packages\jittor
[i 0407 16:09:30.220000 88 compiler.py:956] cl at D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe(19.29.30133)
[i 0407 16:09:30.221000 88 compiler.py:957] cache_path: D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default
[i 0407 16:09:30.273000 88 install_cuda.py:93] cuda_driver_version: [12, 1, 0]
[i 0407 16:09:30.401000 88 __init__.py:411] Found D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe(11.2.67) at D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin\nvcc.exe.
[i 0407 16:09:30.560000 88 compiler.py:1010] cuda key:cu11.2.67
[i 0407 16:09:30.563000 88 __init__.py:227] Total mem: 15.92GB, using 5 procs for compiling.
[i 0407 16:09:37.958000 88 jit_compiler.cc:28] Load cc_path: D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe
[i 0407 16:09:38.058000 88 init.cc:62] Found cuda archs: [50,]
[i 0407 16:09:38.174000 88 compile_extern.py:522] mpicc not found, distribution disabled.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:   0%|                                                                 | 0/8 [00:00<?, ?it/s][e 0407 16:10:24.366000 88 log.cc:565] cl : Command line warning D9025 : overriding '/Os' with '/Ot'
cl : Command line warning D9002 : ignoring unknown option '-Of'
cl : Command line warning D9002 : ignoring unknown option '-Oa'
getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc
D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc(28): warning C4068: unknown pragma 'GCC'
D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc : fatal error C1083: Cannot open compiler generated file: '': Invalid argument

Loading checkpoint shards:   0%|                                                                 | 0/8 [00:26<?, ?it/s]
Traceback (most recent call last):
  File "web_demo.py", line 26, in <module>
    model = models.get_model(args)
  File "D:\Jianan\Develop\github\JittorLLMs\models\__init__.py", line 42, in get_model
    return module.get_model(args)
  File "D:\Jianan\Develop\github\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "D:\Jianan\Develop\github\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2812, in _load_pretrained_model
    error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 491, in _load_state_dict_into_model
    load(model_to_load, state_dict, prefix=start_prefix)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 485, in load
    module._load_from_state_dict(*args)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\jittor\__init__.py", line 1342, in _load_from_state_dict
    self.load_state_dict(state)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\jtorch\__init__.py", line 104, in load_state_dict
    return super().load_state_dict(state_dict)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\jittor\__init__.py", line 1333, in load_state_dict
    self.load_parameters(params)
  File "D:\Jianan\Win\Anaconda3\envs\jittor\lib\site-packages\jittor\__init__.py", line 1594, in load_parameters
    v.sync(False, False)
RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.sync)).

Types of your inputs are:
 self   = Var,
 args   = (bool, bool, ),

The function declarations are:
 VarHolder* sync(bool device_sync = false, bool weak_sync = true)

Failed reason:[f 0407 16:10:24.462000 88 parallel_compiler.cc:330] Error happend during compilation:
 [Error] source file location:D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc
Compile operator(0/1)failed:Op(6386:0:1:1:i1:o1:s0,getitem.bool->6387)

Reason: [f 0407 16:10:24.367000 88 log.cc:608] Check failed ret(1) == 0(0) Run cmd failed: "D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\VC\_\_\_\_\_\bin\cl.exe" "D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc" -Fe: "D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.dll"   -std:c++17      -LD   -EHa -MD -utf-8  -nologo -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\VC\include" -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\win10_kits\include\ucrt" -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\win10_kits\include\shared" -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\win10_kits\include\um" -DNOMINMAX   -I"d:\jianan\win\anaconda3\envs\jittor\lib\site-packages\jittor\src" -I"d:\jianan\win\anaconda3\envs\jittor\include" -DHAS_CUDA -DIS_CUDA -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\include" -I"d:\jianan\win\anaconda3\envs\jittor\lib\site-packages\jittor\extern\cuda\inc"   -I"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67"    -Ofast  -link -LIBPATH:"d:\jianan\win\anaconda3\envs\jittor\libs" python38.lib -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\VC\lib" -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\win10_kits\lib\um\x64" -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\msvc\win10_kits\lib\ucrt\x64" cudart.lib -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\lib\x64" -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jtcuda\cuda11.2_cudnn8_win\bin" -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67" -LIBPATH:"D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome\.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default" "jit_utils_core.cp38-win_amd64".lib "jittor_core.cp38-win_amd64".lib  -EXPORT:"?jit_run@GetitemOp@jittor@@QEAAXXZ"

**Comment by cjld** [comment]
请问cli_demo.py能正常问答吗？

**Comment by cjld** [comment]
还需要您提供下错误信息中这个文件的具体内容：`source file location:D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc`

**Comment by qinxiandiqi** [comment]
不好意思，那台电脑现在不在身边，要下周二才能再拿到，拿到再回复你哈

**Comment by qinxiandiqi** [comment]
> 还需要您提供下错误信息中这个文件的具体内容：`source file location:D:\Jianan\Win\Anaconda3\envs\jittor\JittorHome.cache\jittor\jt1.3.7\cl\py3.8.16\Windows-10-10.x04\IntelRCoreTMi7x3b\default\cu11.2.67\jit\getitem__Ti_float16__IDIM_1__ODIM_1__IV0_0__IO0_0__VS0_1__JIT_1__JIT_cpu_1__index_t_int32_hash_eaf0bc6f85e36896_op.cc`


内容如下：
`#define JIT 1
#define JIT_cpu 1






#include <cmath>
#include "var.h"
#include "executor.h"
#include "ops/getitem_op.h"
#include "ops/op_register.h"
#include "type/fp16_compute.h"
#define getitem 
#define Ti float16
#define IDIM 1
#define ODIM 1
#define IV0 0
#define IO0 0
#define VS0 1
#define index_t int32

namespace jittor {



#pragma GCC diagnostic ignored "-Wunused-variable"

void GetitemOp::jit_run() {
    auto in = inputs().front();
    auto out = outputs().front();
    if (out->num == 0) return;
    if (ns.get(GetitemOp::_inplace) &&
        in->allocator == out->allocator &&
        in->allocation == out->allocation)
        return;

     index_t oshape0 = o_shape[0];
    
        index_t ostride0 = 1;
        
    
    Ti* op = out->ptr<Ti>();

    Ti* ip = in->ptr<Ti>();
     index_t ishape0 = 
        
        in->shape[0];
    
    index_t istride0 = 1;
    

    
     
         
            index_t vstart0 = vs.slices[0].slice.start;
            index_t vstep0 = 1;
        
    
    
     
        
    
    
     
        
    
    
    

     for (index_t i0=0; i0 < oshape0; i0++) {
        index_t oid = 0  + i0 * ostride0;
         index_t iid0 = 
            
            
             (i0*vstep0+vstart0);
        
        auto iid = 0   + iid0 * istride0;
        op[oid] = ip[iid];
    }
}


} 

`

**Comment by sticktoFE** [comment]
应该是修改JITTOR_HOME位置了，我修改到D盘就会报这个问题，保持C盘没问题，我的32G内存，8g显存（nVidia 2080）风险狂转，根本跑不起来

**Comment by qinxiandiqi** [comment]
> 应该是修改JITTOR_HOME位置了，我修改到D盘就会报这个问题，保持C盘没问题，我的32G内存，8g显存（nVidia 2080）风险狂转，根本跑不起来

对，我就是修改了JITOR_HOME，C盘空间不够啊
