### ISSUE TITLE
Loading Check Points出问题

### ISSUE THREAD

**Issue by Chaorilito** [Jittor/JittorLLMs#39]

**Comment by Chaorilito** [comment]
Loading checkpoint shards:  75%|██████████████████████████████████████████▊              | 6/8 [00:23<00:07,  3.92s/it]
Traceback (most recent call last):
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py", line 228, in load
    return jt.load(path)
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 1124, in load
    model_dict = safeunpickle(path)
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 221, in load_pytorch
    result = unpickler.load()
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 44, in persistent_load
    load_tensor(contents, dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor_utils\load_pytorch.py", line 21, in load_tensor
    loaded_storages[key] = contents.read_var(name, dtype)
RuntimeError: [f 0409 09:55:46.379000 80 executor.cc:691] Check failed: v->mem_ptr || v->flags.get(NodeFlags::_is_swapped) || !v->backward_liveness  Something wrong... Could you please report this issue?
 Var(11278:2:2:2:i0:o0:s1:n0,float16,,0)[67108864,]
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 64: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ChatGLM\Desktop\JittorLLMs\web_demo.py", line 26, in <module>
    model = models.get_model(args)
  File "C:\Users\ChatGLM\Desktop\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "C:\Users\ChatGLM\Desktop\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "C:\Users\ChatGLM\Desktop\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\ChatGLM\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'C:\Users\ChatGLM\Desktop\JittorLLMs\models\chatglm\pytorch_model-00007-of-00008.bin' at 'C:\Users\ChatGLM\Desktop\JittorLLMs\models\chatglm\pytorch_model-00007-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
请按任意键继续. . .

**Comment by Chaorilito** [comment]
模型是他自己下载的，已经删掉重下过 仍然是同一个模型出问题

**Comment by Chaorilito** [comment]
系统盘虚拟内存不足
已更改虚拟内存到其他高速盘  并且设了32GB
已更改JittorLLMs的cache到其他空间充裕的高速盘
成功运行

**Comment by af913337456** [comment]
也解决了，但不是你这个解决方法

**Comment by yunlianwangluo** [comment]
服务器8核32G，第一次交互没有限制内存数据，直接killed。第二次设置了内存配置，交互的时候卡死了
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a configuration with custom code to ensure no malicious code has been contributed in a newer revision.
Explicitly passing a `revision` is encouraged when loading a model with custom code to ensure no malicious code has been contributed in a newer revision.
Loading checkpoint shards:  50%|███████████▌           | 4/8 [00:57<01:03, 15.82s/it]Loading checkpoint shards: 100%|███████████████████████| 8/8 [01:52<00:00, 14.08s/it]
用户输入:介绍下你自己

**Comment by KuangShaoK** [comment]
> 

可以分享下思路么

**Comment by cheng31869** [comment]
@af913337456 你是怎么解决的啊，我反复报这个错。
@Chaorilito https://github.com/Jittor/JittorLLMs/issues/39#issuecomment-1501025656 如何设置虚拟内存的位置，是在系统属性里面吗?jittor_cache环境变量我也设置了，cache成功改到充足的高速盘了，但是错误不变

**Comment by cheng31869** [comment]
https://github.com/Jittor/JittorLLMs/issues/39#issuecomment-1596528363 系统属性里面那个交换内存我给设置了70多G的上限呢

**Comment by venxzw** [comment]
@af913337456 您好，能够分享一下解决方法吗，非常感谢
