### ISSUE TITLE
[i 0403 20:52:58.337000 36 compile_extern.py:522] mpicc not found, distribution disabled.

### ISSUE THREAD

**Issue by bearworks** [Jittor/JittorLLMs#4]
Traceback (most recent call last):
  File "E:\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "E:\JittorLLMs\models\__init__.py", line 42, in get_model
    return module.get_model(args)
  File "E:\JittorLLMs\models\chatglm\__init__.py", line 40, in get_model
    return ChatGLMMdoel(args)
  File "E:\JittorLLMs\models\chatglm\__init__.py", line 19, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 663, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 388, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 269, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 134, in check_imports
    importlib.import_module(imp)
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\icetk\__init__.py", line 1, in <module>
    from .ice_tokenizer import IceTokenizer
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\icetk\ice_tokenizer.py", line 9, in <module>
    import torch
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\__init__.py", line 5, in <module>
    import jtorch
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\__init__.py", line 10, in <module>
    import jtorch.compiler
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch\compiler.py", line 25, in <module>
    jt.compiler.compile(
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 156, in compile
    do_compile(fix_cl_flags(cmd))
  File "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jittor\compiler.py", line 89, in do_compile
    return jit_utils.cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0403 20:52:59.986000 36 cache_compile.cc:266] Check failed: src.size()  Something wrong... Could you please report this issue?
 Source read failed: E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch/src\data.obj cmd: "e:\users\administrator\appdata\local\programs\python\python310\python.exe" "e:\users\administrator\appdata\local\programs\python\python310\lib\site-packages\jittor\utils\dumpdef.py" "C:\Users\Administrator\.cache\jittor\jt1.3.7\cl\py3.10.10\Windows-10-10.x91\IntelRXeonRCPUx6b\default\jtorch_objs\pyjt_jtorch_core.cc.obj" "C:\Users\Administrator\.cache\jittor\jt1.3.7\cl\py3.10.10\Windows-10-10.x91\IntelRXeonRCPUx6b\default\jtorch_objs\pyjt_all.cc.obj" "E:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\jtorch/src\data.obj" -Fo: "C:\Users\Administrator\.cache\jittor\jt1.3.7\cl\py3.10.10\Windows-10-10.x91\IntelRXeonRCPUx6b\default\jtorch_core.cp310-win_amd64.pyd.def"

**Comment by Jittor** [comment]
谢谢反馈，这个是windows安装相关的问题，我们正在fix，您可以先试试在wsl下运行。修复好后我们将通知您。

**Comment by cjld** [comment]
请将jittor更新至1.3.7.3， jtorch更新到0.1.3， jittorllms更新到最新可修复该问题

**Comment by bearworks** [comment]
这个问题好了，谢谢
