### ISSUE TITLE
运行报RuntimeError错误

### ISSUE THREAD

**Issue by shaneluik1026** [Jittor/JittorLLMs#42]
(jittor) andy@ai:/code/source/ai/JittorLLMs$ python cli_demo.py chatglm
[i 0409 19:39:54.648478 12 compiler.py:955] Jittor(1.3.7.12) src: /code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor
[i 0409 19:39:54.652741 12 compiler.py:956] g++ at /usr/bin/g++(11.3.0)
[i 0409 19:39:54.652926 12 compiler.py:957] cache_path: /home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default
[i 0409 19:39:54.669861 12 install_cuda.py:93] cuda_driver_version: [11, 8]
[i 0409 19:39:54.670362 12 install_cuda.py:81] restart /code/linux/anaconda3/envs/jittor/bin/python ['cli_demo.py', 'chatglm']
[i 0409 19:39:54.814949 88 compiler.py:955] Jittor(1.3.7.12) src: /code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor
[i 0409 19:39:54.818949 88 compiler.py:956] g++ at /usr/bin/g++(11.3.0)
[i 0409 19:39:54.819099 88 compiler.py:957] cache_path: /home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default
[i 0409 19:39:54.835834 88 install_cuda.py:93] cuda_driver_version: [11, 8]
[i 0409 19:39:54.840973 88 __init__.py:411] Found /home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc(11.2.152) at /home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc.
[i 0409 19:39:54.900603 88 __init__.py:411] Found gdb(12.1) at /usr/bin/gdb.
[i 0409 19:39:54.905797 88 __init__.py:411] Found addr2line(2.38) at /usr/bin/addr2line.
[i 0409 19:39:55.047044 88 compiler.py:1010] cuda key:cu11.2.152_sm_75
[i 0409 19:39:55.281029 88 __init__.py:227] Total mem: 31.29GB, using 10 procs for compiling.
/usr/include/stdio.h(189): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(201): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(223): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(260): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(285): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(294): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(303): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(309): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(315): error: attribute "__malloc__" does not take arguments

/usr/include/stdio.h(830): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(566): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(570): error: attribute "__malloc__" does not take arguments

/usr/include/stdlib.h(799): error: attribute "__malloc__" does not take arguments

/usr/include/c++/11/type_traits(1406): error: type name is not allowed

/usr/include/c++/11/type_traits(1406): error: type name is not allowed

/usr/include/c++/11/type_traits(1406): error: identifier "__is_same" is undefined

/usr/include/wchar.h(155): error: attribute "__malloc__" does not take arguments

/usr/include/wchar.h(582): error: attribute "__malloc__" does not take arguments

/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/cstr.h(19): error: no instance of overloaded function "std::unique_ptr<_Tp [], _Dp>::reset [with _Tp=char, _Dp=std::default_delete<char []>]" matches the argument list
            argument types are: (char *)
            object type is: jittor::unique_ptr<char []>

/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/cstr.h(25): error: no instance of overloaded function "std::unique_ptr<_Tp [], _Dp>::reset [with _Tp=char, _Dp=std::default_delete<char []>]" matches the argument list
            argument types are: (char *)
            object type is: jittor::unique_ptr<char []>

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6620): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6625): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6630): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6635): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=char, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6640): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6646): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6650): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=char, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6654): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<int, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=int, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6751): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long, std::is_same<long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long, _Ret=long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6756): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long, std::is_same<unsigned long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long, _Ret=unsigned long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6761): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long long, std::is_same<long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long long, _Ret=long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6766): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const unsigned long long, std::is_same<unsigned long long, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=unsigned long long, _Ret=unsigned long long, _CharT=wchar_t, _Base=<int>]" 
/usr/include/c++/11/bits/basic_string.h(6771): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const float, std::is_same<float, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=float, _Ret=float, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6777): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const double, std::is_same<double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=double, _Ret=double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6781): here

/usr/include/c++/11/ext/string_conversions.h(85): error: no instance of overloaded function "_Range_chk::_S_chk" matches the argument list
            argument types are: (const long double, std::is_same<long double, int>)
          detected during instantiation of "_Ret __gnu_cxx::__stoa(_TRet (*)(const _CharT *, _CharT **, _Base...), const char *, const _CharT *, std::size_t *, _Base...) [with _TRet=long double, _Ret=long double, _CharT=wchar_t, _Base=<>]" 
/usr/include/c++/11/bits/basic_string.h(6785): here

36 errors detected in the compilation of "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu".
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor_utils/__init__.py", line 197, in do_compile
    return cc.cache_compile(cmd, cache_path, jittor_path)
RuntimeError: [f 0409 19:39:57.996372 88 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc"  "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src" -I/code/linux/anaconda3/envs/jittor/include/python3.7m -I/code/linux/anaconda3/envs/jittor/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc"   -I"/home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default/cu11.2.152_sm_75"   -O2   -c -o "/home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default/cu11.2.152_sm_75/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc" 
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/code/source/ai/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/code/source/ai/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/code/source/ai/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/compiler.py", line 1353, in <module>
    compile(cc_path, cc_flags+opt_flags, files, 'jittor_core'+extension_suffix)
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/compiler.py", line 151, in compile
    jit_utils.run_cmds(cmds, cache_path, jittor_path, "Compiling "+base_output)
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor_utils/__init__.py", line 251, in run_cmds
    for i,_ in enumerate(p.imap_unordered(do_compile, cmds)):
  File "/code/linux/anaconda3/envs/jittor/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
RuntimeError: [f 0409 19:39:57.996372 88 log.cc:608] Check failed ret(256) == 0(0) Run cmd failed: "/home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/bin/nvcc"  "/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src/misc/nan_checker.cu"     -std=c++14 -Xcompiler -fPIC  -Xcompiler -march=native  -Xcompiler -fdiagnostics-color=always   -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/src" -I/code/linux/anaconda3/envs/jittor/include/python3.7m -I/code/linux/anaconda3/envs/jittor/include/python3.7m -DHAS_CUDA -DIS_CUDA -I"/home/andy/.cache/jittor/jtcuda/cuda11.2_cudnn8_linux/include" -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc"   -I"/home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default/cu11.2.152_sm_75"   -O2   -c -o "/home/andy/.cache/jittor/jt1.3.7/g++11.3.0/py3.7.16/Linux-5.19.0-3x69/IntelRCoreTMi5xda/default/cu11.2.152_sm_75/obj_files/nan_checker.cu.o" -x cu --cudart=shared -ccbin="/usr/bin/g++"   -w  -I"/code/linux/anaconda3/envs/jittor/lib/python3.7/site-packages/jittor/extern/cuda/inc"

**Comment by Aneeskhalil** [comment]
LOL
