### ISSUE TITLE
Compiling Problems

### ISSUE THREAD

**Issue by jiayaozhang** [Jittor/JittorLLMs#5]
Thanks for releasing source code of this amazing work. 
I was able to run chatglm successfully, but when i run pangualpha, shows below errors.

How to fix this then？ Many thanks!

`python3 cli_demo.py  pangualpha`

```python
WARNING: APEX is not installed, multi_tensor_applier will not be available.
WARNING: APEX is not installed, using torch.nn.LayerNorm instead of apex.normalization.FusedLayerNorm!
Traceback (most recent call last):
  File "/home/janice/Documents/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/janice/Documents/JittorLLMs/models/__init__.py", line 41, in get_model
    module = importlib.import_module(f"models.{model_name}")
  File "/home/janice/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/janice/Documents/JittorLLMs/models/pangualpha/__init__.py", line 6, in <module>
    from megatron.text_generation_utils import pad_batch, get_batch
  File "/home/janice/Documents/JittorLLMs/models/pangualpha/megatron/text_generation_utils.py", line 29, in <module>
    from megatron.utils import get_ltor_masks_and_position_ids
  File "/home/janice/Documents/JittorLLMs/models/pangualpha/megatron/utils.py", line 27, in <module>
    from megatron.data.samplers import DistributedBatchSampler
  File "/home/janice/Documents/JittorLLMs/models/pangualpha/megatron/data/samplers.py", line 22, in <module>
    class RandomSampler(data.sampler.Sampler):
AttributeError: module 'jtorch.utils.data' has no attribute 'sampler'
```

I have updated jittor to 1.3.7.3， jtorch to 0.1.3

**Comment by cjld** [comment]
谢谢您的反馈，jittor更新到1.3.7.4即可

**Comment by jiayaozhang** [comment]
谢谢您的支持，更新到最新版本以后，全部问题都解决了！ 
测试 Linux 系统 4090 & Window 系统 3070 均跑通
