### ISSUE TITLE
ERROR:'import jittor as jt' 启动报错

### ISSUE THREAD

**Issue by wangtaihong** [Jittor/JittorLLMs#56]
环境：centos7.6
gcc5.5
python3.9.6
venv环境：
Package                  Version
------------------------ ----------
astunparse               1.6.3
certifi                  2022.12.7
charset-normalizer       3.1.0
cmake                    3.26.1
filelock                 3.11.0
idna                     3.4
Jinja2                   3.1.2
jittor                   1.3.7.13
jtorch                   0.1.3
lit                      16.0.0
MarkupSafe               2.1.2
mpmath                   1.3.0
networkx                 3.1
numpy                    1.24.2
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
Pillow                   9.5.0
pip                      21.1.3
requests                 2.28.2
setuptools               56.0.0
six                      1.16.0
sympy                    1.11.1
torch                    2.0.0
torchvision              0.15.1
tqdm                     4.65.0
triton                   2.0.0
typing-extensions        4.5.0
urllib3                  1.26.15
wheel                    0.40.0

error信息：
(venv) [root@spark3 JittorLLMs]# python3.9 cli_demo.py chatglm
[i 0421 22:13:57.729055 52 lock.py:85] Create lock file:/root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/jittor.lock
[i 0421 22:13:57.787668 52 compiler.py:955] Jittor(1.3.7.13) src: /home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor
[i 0421 22:13:57.791861 52 compiler.py:956] g++ at /usr/local/bin/g++(5.5.0)
[i 0421 22:13:57.792003 52 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main
[i 0421 22:13:58.022211 52 __init__.py:411] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0421 22:13:58.082315 52 __init__.py:411] Found addr2line(2.27) at /usr/bin/addr2line.
[i 0421 22:13:58.231147 52 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main/jit
[i 0421 22:13:58.231660 52 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main/obj_files
[i 0421 22:13:58.232122 52 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main/gen
[i 0421 22:13:58.232666 52 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main/tmp
[i 0421 22:13:58.232992 52 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main/checkpoints
Traceback (most recent call last):
  File "/home/hadoop/LLM/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/hadoop/LLM/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 891, in check_cache_compile
    assert jit_utils.cc
AssertionError
(venv) [root@spark3 JittorLLMs]# python3.9 cli_demo.py pangualpha
Traceback (most recent call last):
  File "/home/hadoop/LLM/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/hadoop/LLM/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 59, in get_pangualpha
    path = download_fromhub(f"jittorhub://model_optim_rng.pth", tdir="pangu")
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 891, in check_cache_compile
    assert jit_utils.cc
AssertionError
(venv) [root@spark3 JittorLLMs]# python3.9 cli_demo.py llama
[i 0421 22:14:58.677402 80 compiler.py:955] Jittor(1.3.7.13) src: /home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor
[i 0421 22:14:58.680254 80 compiler.py:956] g++ at /usr/local/bin/g++(5.5.0)
[i 0421 22:14:58.680356 80 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++5.5.0/py3.9.6/Linux-3.10.0-1xca/IntelRCoreTMi3x4a/main
[i 0421 22:14:58.701887 80 __init__.py:411] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0421 22:14:58.705072 80 __init__.py:411] Found addr2line(2.27) at /usr/bin/addr2line.
Traceback (most recent call last):
  File "/home/hadoop/LLM/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/home/hadoop/LLM/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 33, in get_llama
    new_paths.append(download_fromhub(f"jittorhub://{f}", tdir="llama"))
  File "/home/hadoop/LLM/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/home/hadoop/LLM/JittorLLMs/venv/lib/python3.9/site-packages/jittor/compiler.py", line 891, in check_cache_compile
    assert jit_utils.cc
AssertionError

**Comment by winnerahao** [comment]
+1

**Comment by ZIYONGONLY** [comment]
+1
