### ISSUE TITLE
请问macos m2 内存64 可以跑盘古吗？目前可以跑chatglm，但盘古报错需要cuda

### ISSUE THREAD

**Issue by bigbencat** [Jittor/JittorLLMs#67]
Traceback (most recent call last):
  File "cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/Users/brucelee/Documents/SynologyDrive/work/AI_Chat/JittorLLMs/models/__init__.py", line 46, in get_model
    return module.get_model(args)
  File "/Users/brucelee/Documents/SynologyDrive/work/AI_Chat/JittorLLMs/models/pangualpha/__init__.py", line 173, in get_model
    return PanGuAlphaModel()
  File "/Users/brucelee/Documents/SynologyDrive/work/AI_Chat/JittorLLMs/models/pangualpha/__init__.py", line 134, in __init__
    initialize_megatron(extra_args_provider=add_text_generate_args,
  File "/Users/brucelee/Documents/SynologyDrive/work/AI_Chat/JittorLLMs/models/pangualpha/megatron/initialize.py", line 44, in initialize_megatron
    assert torch.cuda.is_available(), 'Megatron requires CUDA.'
AssertionError: Megatron requires CUDA.

**Comment by bigbencat** [comment]
https://openi.pcl.ac.cn/PCL-Platform.Intelligence/pcl_pangu/src/branch/master/docs/README_InferCpu.md
