### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by wwjCMP** [Jittor/JittorLLMs#79]
Traceback (most recent call last):
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 415, in load_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jtorch\__init__.py", line 228, in load
    return jt.load(path)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor\__init__.py", line 1124, in load
    model_dict = safeunpickle(path)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor\__init__.py", line 98, in safeunpickle
    model_dict = load_pytorch(path)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor_utils\load_pytorch.py", line 221, in load_pytorch
    result = unpickler.load()
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor_utils\load_pytorch.py", line 44, in persistent_load
    load_tensor(contents, dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\jittor_utils\load_pytorch.py", line 21, in load_tensor
    loaded_storages[key] = contents.read_var(name, dtype)
RuntimeError: [f 0429 08:09:39.193000 48 executor.cc:691] Check failed: v->mem_ptr || v->flags.get(NodeFlags::_is_swapped) || !v->backward_liveness  Something wrong... Could you please report this issue?
 Var(10519:2:2:2:i0:o0:s1:n0,float16,,0)[67108864,]
**********
Async error was detected. To locate the async backtrace and get better error report, please rerun your code with two enviroment variables set:
cmd:
>>> set JT_SYNC=1
>>> set trace_py_var=3
powershell:
>>> $env:JT_SYNC=1
>>> $env:trace_py_var=3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 64: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\JittorLLMs\cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "I:\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "I:\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "I:\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'I:\JittorLLMs\models\chatglm\pytorch_model-00006-of-00008.bin' at 'I:\JittorLLMs\models\chatglm\pytorch_model-00006-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by wwjCMP** [comment]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 419, in load_state_dict
    if f.read(7) == "version":
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 64: illegal multibyte sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\JittorLLMs\web_demo.py", line 26, in <module>
    model = models.get_model(args)
  File "I:\JittorLLMs\models\__init__.py", line 46, in get_model
    return module.get_model(args)
  File "I:\JittorLLMs\models\chatglm\__init__.py", line 48, in get_model
    return ChatGLMMdoel(args)
  File "I:\JittorLLMs\models\chatglm\__init__.py", line 22, in __init__
    self.model = AutoModel.from_pretrained(os.path.dirname(__file__), trust_remote_code=True)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\models\auto\auto_factory.py", line 459, in from_pretrained
    return model_class.from_pretrained(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2478, in from_pretrained
    ) = cls._load_pretrained_model(
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 2780, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "C:\Users\wwj93\Anaconda3\envs\jittor\lib\site-packages\transformers\modeling_utils.py", line 431, in load_state_dict
    raise OSError(
OSError: Unable to load weights from pytorch checkpoint file for 'I:\JittorLLMs\models\chatglm\pytorch_model-00006-of-00008.bin' at 'I:\JittorLLMs\models\chatglm\pytorch_model-00006-of-00008.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by KuangShaoK** [comment]
你好，请问closed是解决了么，我也碰上同样问题了可以给建议么
