### ISSUE TITLE
在一个没有GPU的服务器上运行cli_demo.py报错

### ISSUE THREAD

**Issue by seanandmengjia** [Jittor/JittorLLMs#82]
请问这个问题如何解决
完整的报错信息如下：
[i 0429 22:40:04.757432 32 lock.py:85] Create lock file:/root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/jittor.lock
[i 0429 22:40:04.777665 32 compiler.py:955] Jittor(1.3.7.14) src: /usr/python3/lib/python3.9/site-packages/jittor
[i 0429 22:40:04.781539 32 compiler.py:956] g++ at /opt/rh/devtoolset-9/root/usr/bin/g++(9.3.1)
[i 0429 22:40:04.781658 32 compiler.py:957] cache_path: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default
[i 0429 22:40:04.810227 32 __init__.py:411] Found gdb(7.6.1) at /usr/bin/gdb.
[i 0429 22:40:04.815026 32 __init__.py:411] Found addr2line(2.32) at /opt/rh/devtoolset-9/root/usr/bin/addr2line.
[i 0429 22:40:04.861565 32 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/jit
[i 0429 22:40:04.861848 32 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/obj_files
[i 0429 22:40:04.862033 32 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/gen
[i 0429 22:40:04.862284 32 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/tmp
[i 0429 22:40:04.862458 32 compiler.py:34] Create cache dir: /root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/checkpoints
In file included from /usr/python3/lib/python3.9/site-packages/jittor/src/utils/jit_utils.cc:8:
/usr/python3/lib/python3.9/site-packages/jittor/src/pyjt/py_converter.h: In function ‘typename std::enable_if<std::is_same<T, jittor::NanoString>::value, T>::type jittor::from_py_object(PyObject*)’:
/usr/python3/lib/python3.9/site-packages/jittor/src/pyjt/py_converter.h:261:18: error: there are no arguments to ‘_PyType_Name’ that depend on a template parameter, so a declaration of ‘_PyType_Name’ must be available [-fpermissive]
  261 |         return T(_PyType_Name((PyTypeObject *)obj));
      |                  ^~~~~~~~~~~~
/usr/python3/lib/python3.9/site-packages/jittor/src/pyjt/py_converter.h:261:18: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/usr/python3/lib/python3.9/site-packages/jittor/src/pyjt/py_converter.h:269:14: error: there are no arguments to ‘_PyType_Name’ that depend on a template parameter, so a declaration of ‘_PyType_Name’ must be available [-fpermissive]
  269 |     return T(_PyType_Name((PyTypeObject *)t.obj));
      |              ^~~~~~~~~~~~
Traceback (most recent call last):
  File "/mnt/chatglm/JittorLLMs/cli_demo.py", line 8, in <module>
    model = models.get_model(args)
  File "/mnt/chatglm/JittorLLMs/models/__init__.py", line 38, in get_model
    globals()[f"get_{model_name}"]()
  File "/mnt/chatglm/JittorLLMs/models/util.py", line 51, in get_chatglm
    new_path.append(download_fromhub(f"jittorhub://{f}", tdir="chat-glm"))
  File "/mnt/chatglm/JittorLLMs/models/util.py", line 5, in download_fromhub
    import jittor as jt
  File "/usr/python3/lib/python3.9/site-packages/jittor/__init__.py", line 18, in <module>
    from . import compiler
  File "/usr/python3/lib/python3.9/site-packages/jittor/compiler.py", line 1189, in <module>
    check_cache_compile()
  File "/usr/python3/lib/python3.9/site-packages/jittor/compiler.py", line 884, in check_cache_compile
    recompile = compile(cc_path, cc_flags+f" {opt_flags} ", files, jit_utils.cache_path+'/jit_utils_core'+extension_suffix, True)
  File "/usr/python3/lib/python3.9/site-packages/jittor/compiler.py", line 126, in compile
    return do_compile(fix_cl_flags(cmd))
  File "/usr/python3/lib/python3.9/site-packages/jittor/compiler.py", line 91, in do_compile
    run_cmd(cmd)
  File "/usr/python3/lib/python3.9/site-packages/jittor_utils/__init__.py", line 188, in run_cmd
    raise Exception(err_msg)
Exception: Run cmd failed: "/opt/rh/devtoolset-9/root/usr/bin/g++" "/usr/python3/lib/python3.9/site-packages/jittor/src/utils/cache_compile.cc" "/usr/python3/lib/python3.9/site-packages/jittor/src/utils/log.cc" "/usr/python3/lib/python3.9/site-packages/jittor/src/utils/tracer.cc" "/usr/python3/lib/python3.9/site-packages/jittor/src/utils/jit_utils.cc" "/usr/python3/lib/python3.9/site-packages/jittor/src/utils/str_utils.cc"   -Wall -Wno-unknown-pragmas -std=c++14 -fPIC  -march=native  -fdiagnostics-color=always  -lstdc++ -ldl -shared  -I"/usr/python3/lib/python3.9/site-packages/jittor/src" -I/usr/include/python3.6m -I/usr/include/python3.6m  -O2   -o "/root/.cache/jittor/jt1.3.7/g++9.3.1/py3.9.6/Linux-3.10.0-1x6f/IntelRXeonRGolxcd/default/jit_utils_core.cpython-36m-x86_64-linux-gnu.so"

**Comment by Crystalxd** [comment]
same error.
